[package]
name = "fable_io"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
arrayvec = "0.7.6"
derive_more = { version = "1.0.0", features = ["from", "display"] }

[dependencies.bytemuck]
features = ["derive"]
version = "1.16.3"
