[package]
name = "open_albion"
version = "0.1.0"
authors = ["Jamen Marz <me@jamen.dev>"]
edition = "2018"
license = "Zlib"
homepage = "https://github.com/jamen/open_albion"
repository = "https://github.com/jamen/open_albion"

[dependencies]
winit = "0.25.0"
wgpu = "0.8.1"
glam = "0.15.1"
vk-shader-macros = "0.2.7"
tokio = { version = "1.6.1", features = [ "rt-multi-thread" ] }
flate2 = "1.0.20"
bcndecode = "0.2.0"
png = "0.16.8"
lalrpop-util = "0.19.5"
regex = "1.5.4"
mint = "0.5.6"

[build-dependencies]
cc = "1.0.68"
lalrpop = "0.19.6"
