[package]
name = "client"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "client"
path = "main.rs"

[dependencies]
env_logger.workspace = true
format.workspace = true
futures.workspace = true
log.workspace = true
renderer.workspace = true
thiserror.workspace = true
winit.workspace = true
