//! Def-type dispatch: maps a wire name to the concrete Rust def type.
//! Single-format (OG retail only).

use crate::def::prelude::*;
use crate::def::binary::control::{ParseControlError, SerializeControlError};
use crate::def::binary::def_binary::DefBody;

// ── GameBody enum ────────────────────────────────────────────────────────────

#[derive(Debug, Clone)]
pub enum GameBody {
    AbilityDef(AbilityDef),
    ActionUseDef(ActionUseDef),
    ActivateQuestDef(ActivateQuestDef),
    AICreatureWillPowerIndicatorDef(AICreatureWillPowerIndicatorDef),
    AIScratchpadDef(AIScratchpadDef),
    AnimatingObjectDef(AnimatingObjectDef),
    AppearanceDef(AppearanceDef),
    AreaOfEffectAttackDef(AreaOfEffectAttackDef),
    ArmourDef(ArmourDef),
    AttackPatternDef(AttackPatternDef),
    AugmentationDef(AugmentationDef),
    BalverineBattleDef(BalverineBattleDef),
    BedDef(BedDef),
    BettingDef(BettingDef),
    BoastingPodiumDef(BoastingPodiumDef),
    BonusItemDef(BonusItemDef),
    BossDef(BossDef),
    BrainDef(BrainDef),
    BriarRoseDef(BriarRoseDef),
    BuyHouseDef(BuyHouseDef),
    BuyableHouseDef(BuyableHouseDef),
    CameraCollisionDef(CameraCollisionDef),
    CameraManagerDef(CameraManagerDef),
    CameraManagerSetDef(CameraManagerSetDef),
    CameraModeDef(CameraModeDef),
    CarriedReadableDef(CarriedReadableDef),
    CarrySlotDef(CarrySlotDef),
    CarryableDef(CarryableDef),
    CarryingDef(CarryingDef),
    ChestDef(ChestDef),
    ClockDef(ClockDef),
    CoinGameObstacleDef(CoinGameObstacleDef),
    CombatAbilityAttackBase(CombatAbilityAttackBase),
    CombatAbilityBlockDefBase(CombatAbilityBlockDefBase),
    CombatAbilityStrafeDef(CombatAbilityStrafeDef),
    CombatAbilityUseProjectileWeaponDef(CombatAbilityUseProjectileWeaponDef),
    CombatDialogueDef(CombatDialogueDef),
    CombatSequenceDef(CombatSequenceDef),
    CombatTypeDef(CombatTypeDef),
    ContainerRewardHeroDef(ContainerRewardHeroDef),
    ContextSensitiveItemDef(ContextSensitiveItemDef),
    CoopSpiritDef(CoopSpiritDef),
    CrateStackDef(CrateStackDef),
    CreatureAbilityDef(CreatureAbilityDef),
    CreatureDef(CreatureDef),
    CreatureGenerationFamilyDef(CreatureGenerationFamilyDef),
    CreatureGeneratorDef(CreatureGeneratorDef),
    CreatureModeDef(CreatureModeDef),
    CreatureNavigationDef(CreatureNavigationDef),
    CreatureStatsDef(CreatureStatsDef),
    CutsceneDef(CutsceneDef),
    DecapitationDef(DecapitationDef),
    DoorDef(DoorDef),
    DragonActionHoverDef(DragonActionHoverDef),
    DragonActionNapalmDef(DragonActionNapalmDef),
    DragonActionSwoopDef(DragonActionSwoopDef),
    DrunkennessDef(DrunkennessDef),
    EnemyDef(EnemyDef),
    EngineLocalDetailGeneratorDef(EngineLocalDetailGeneratorDef),
    EngineThemeDef(EngineThemeDef),
    EngineThemeGroupDef(EngineThemeGroupDef),
    EntitySoundDef(EntitySoundDef),
    ExperienceDef(ExperienceDef),
    ExplodingObjectDef(ExplodingObjectDef),
    ExplosionDef(ExplosionDef),
    ExplosiveTrailDef(ExplosiveTrailDef),
    ExpressionDef(ExpressionDef),
    ExpressionSubDef(ExpressionSubDef),
    FactionDef(FactionDef),
    FireballSpellLevelDef(FireballSpellLevelDef),
    FireheartMinigameDef(FireheartMinigameDef),
    FishDef(FishDef),
    FishingDef(FishingDef),
    FishingRodDef(FishingRodDef),
    FlammableDef(FlammableDef),
    GiftDef(GiftDef),
    GoldDef(GoldDef),
    GuardDef(GuardDef),
    GuildMasterDef(GuildMasterDef),
    HairCardDef(HairCardDef),
    HasNameDef(HasNameDef),
    HeroAbilityDef(HeroAbilityDef),
    HeroCentreDef(HeroCentreDef),
    HeroCombatDef(HeroCombatDef),
    HeroDef(HeroDef),
    HeroExperienceDef(HeroExperienceDef),
    HeroMarriageDef(HeroMarriageDef),
    HeroMorphDef(HeroMorphDef),
    HeroPostcardGeneratorDef(HeroPostcardGeneratorDef),
    HeroSpecialMovementDef(HeroSpecialMovementDef),
    HeroStatsDef(HeroStatsDef),
    HeroSuitDef(HeroSuitDef),
    HeroTitleDef(HeroTitleDef),
    HighlightItemDef(HighlightItemDef),
    HitLocationDef(HitLocationDef),
    HitLocationsDef(HitLocationsDef),
    IdleSchedulerDef(IdleSchedulerDef),
    InterestingToVillagersDef(InterestingToVillagersDef),
    InventoryCategoryDef(InventoryCategoryDef),
    InventoryDef(InventoryDef),
    InventoryItemDef(InventoryItemDef),
    JackDragonDef(JackDragonDef),
    JackOfBladesBattleDef(JackOfBladesBattleDef),
    KickableDef(KickableDef),
    KrakenDef(KrakenDef),
    KrakenTentacleDef(KrakenTentacleDef),
    LightDef(LightDef),
    LightningDef(LightningDef),
    LightningOrbDef(LightningOrbDef),
    LookDef(LookDef),
    MaterialDef(MaterialDef),
    MazeBattleDef(MazeBattleDef),
    MeleeCombatAbilityDef(MeleeCombatAbilityDef),
    MeleeCombatKnockdownEffects(MeleeCombatKnockdownEffects),
    MessageEventDef(MessageEventDef),
    MultiStaticMeshDef(MultiStaticMeshDef),
    NymphDef(NymphDef),
    ObjectAugmentationsDef(ObjectAugmentationsDef),
    ObjectFamilyDef(ObjectFamilyDef),
    OccupiableDef(OccupiableDef),
    OpinionDeedEffectsDef(OpinionDeedEffectsDef),
    OpinionDeedMaskDef(OpinionDeedMaskDef),
    OpinionOfHeroDef(OpinionOfHeroDef),
    OpinionPersonalityDef(OpinionPersonalityDef),
    OpinionReactionManagerDef(OpinionReactionManagerDef),
    OpinionReactionMaskDef(OpinionReactionMaskDef),
    OpinionSourceDef(OpinionSourceDef),
    OracleMinigameDef(OracleMinigameDef),
    OverheadDisplayDef(OverheadDisplayDef),
    ParticleAttacherDef(ParticleAttacherDef),
    PerceivedThingDef(PerceivedThingDef),
    PhysicsDef(PhysicsDef),
    PlayerDef(PlayerDef),
    PlayerGuiDef(PlayerGuiDef),
    PlayerInventoryDef(PlayerInventoryDef),
    QuestCardDef(QuestCardDef),
    ReadableDef(ReadableDef),
    RegionDef(RegionDef),
    RegionScriptDef(RegionScriptDef),
    ResurrectionItemDef(ResurrectionItemDef),
    RumbleDef(RumbleDef),
    ScorpionKingBattleDef(ScorpionKingBattleDef),
    ScriptDef(ScriptDef),
    ShipDef(ShipDef),
    SimBuildingDef(SimBuildingDef),
    SimVoicesDef(SimVoicesDef),
    SkeletalMorphDef(SkeletalMorphDef),
    SkyDef(SkyDef),
    SmashableDef(SmashableDef),
    SmokeGeneratorDef(SmokeGeneratorDef),
    SnowTrollDef(SnowTrollDef),
    SoundAtmospheresDef(SoundAtmospheresDef),
    SoundDef(SoundDef),
    SoundThemeDef(SoundThemeDef),
    SpecialAbilitiesAssassinRushDef(SpecialAbilitiesAssassinRushDef),
    SpecialAbilitiesBattleChargeDef(SpecialAbilitiesBattleChargeDef),
    SpecialAbilitiesBerserkDef(SpecialAbilitiesBerserkDef),
    SpecialAbilitiesBulletTimeDef(SpecialAbilitiesBulletTimeDef),
    SpecialAbilitiesBurntEffectDef(SpecialAbilitiesBurntEffectDef),
    SpecialAbilitiesCreatureTintDef(SpecialAbilitiesCreatureTintDef),
    SpecialAbilitiesDrainLifeDef(SpecialAbilitiesDrainLifeDef),
    SpecialAbilitiesDrunkennessDef(SpecialAbilitiesDrunkennessDef),
    SpecialAbilitiesElectrocutedEffectDef(SpecialAbilitiesElectrocutedEffectDef),
    SpecialAbilitiesEnflameDef(SpecialAbilitiesEnflameDef),
    SpecialAbilitiesFireballSpellDef(SpecialAbilitiesFireballSpellDef),
    SpecialAbilitiesForcePushDataDef(SpecialAbilitiesForcePushDataDef),
    SpecialAbilitiesForcePushDef(SpecialAbilitiesForcePushDef),
    SpecialAbilitiesGhostSwordDef(SpecialAbilitiesGhostSwordDef),
    SpecialAbilitiesHealLifeDef(SpecialAbilitiesHealLifeDef),
    SpecialAbilitiesLightningSpellDef(SpecialAbilitiesLightningSpellDef),
    SpecialAbilitiesMultiArrowDef(SpecialAbilitiesMultiArrowDef),
    SpecialAbilitiesMultiStrikeDef(SpecialAbilitiesMultiStrikeDef),
    SpecialAbilitiesPhysicalShieldDef(SpecialAbilitiesPhysicalShieldDef),
    SpecialAbilitiesSummonSpellDef(SpecialAbilitiesSummonSpellDef),
    SpecialAbilitiesThunderLightningStormDef(SpecialAbilitiesThunderLightningStormDef),
    SpecialAbilitiesTurncoatSpellDef(SpecialAbilitiesTurncoatSpellDef),
    SpecialAbilitiesUnholyPowerDef(SpecialAbilitiesUnholyPowerDef),
    SpecialEffectsDef(SpecialEffectsDef),
    SpotLightDef(SpotLightDef),
    StealthDef(StealthDef),
    StockItemDef(StockItemDef),
    SummonDef(SummonDef),
    SummonableCreatureDef(SummonableCreatureDef),
    SummonerDef(SummonerDef),
    TCVolumeContainmentTrackerDef(TCVolumeContainmentTrackerDef),
    TargetingDef(TargetingDef),
    TattooDef(TattooDef),
    TavernDef(TavernDef),
    TavernGameCardBaseDef(TavernGameCardBaseDef),
    TavernGameCoinBaseDef(TavernGameCoinBaseDef),
    TavernGameCoinGolfDef(TavernGameCoinGolfDef),
    TavernGameDef(TavernGameDef),
    TavernGameShoveHaPennyDef(TavernGameShoveHaPennyDef),
    TavernGameSpotTheAdditionDef(TavernGameSpotTheAdditionDef),
    TavernTableDef(TavernTableDef),
    TeleporterDef(TeleporterDef),
    TextureReplacementDef(TextureReplacementDef),
    ThingBaseDef(ThingBaseDef),
    ThingBuildingDef(ThingBuildingDef),
    ThingCreatureDef(ThingCreatureDef),
    ThingDrainLifeShotDef(ThingDrainLifeShotDef),
    ThingHolySiteDef(ThingHolySiteDef),
    ThingMarkerDef(ThingMarkerDef),
    ThingMultiArrowShotDef(ThingMultiArrowShotDef),
    ThingNoiseDef(ThingNoiseDef),
    ThingObjectDef(ThingObjectDef),
    ThingPhysicalSwitchDef(ThingPhysicalSwitchDef),
    ThingShotDef(ThingShotDef),
    ThingSwitchDef(ThingSwitchDef),
    ThingVillageDef(ThingVillageDef),
    ThunderBattleDef(ThunderBattleDef),
    TimeAppearanceFadeDef(TimeAppearanceFadeDef),
    TrapDef(TrapDef),
    TrollBattleDef(TrollBattleDef),
    TrophyDef(TrophyDef),
    TurncoatDef(TurncoatDef),
    UILocaleGraphicsDef(UILocaleGraphicsDef),
    UiMiscThingsDef(UiMiscThingsDef),
    VillageDef(VillageDef),
    VillageMemberDef(VillageMemberDef),
    VillagePeopleDef(VillagePeopleDef),
    VillagerInteractionsDef(VillagerInteractionsDef),
    WallMountEffectsDef(WallMountEffectsDef),
    WaspQueenBattleDef(WaspQueenBattleDef),
    WeaponDef(WeaponDef),
    WhisperBattleDef(WhisperBattleDef),
    WifeDef(WifeDef),
    WillResponseDef(WillResponseDef),
    DegradableDef(DegradableDef),
    ReplaceableMeshDef(ReplaceableMeshDef),
    GlobalDef(GlobalDef),
    PlayerMovementDef(PlayerMovementDef),
    AppearanceModifierDef(AppearanceModifierDef),
    ShopDef(ShopDef),
    ShopItemDef(ShopItemDef),
}

impl GameBody {
    pub fn serialize(&self, out: &mut &mut [u8]) -> Result<(), SerializeControlError> {
        match self {
            Self::AbilityDef(d) => AbilityDef::serialize(d, out),
            Self::ActionUseDef(d) => ActionUseDef::serialize(d, out),
            Self::ActivateQuestDef(d) => ActivateQuestDef::serialize(d, out),
            Self::AICreatureWillPowerIndicatorDef(d) => AICreatureWillPowerIndicatorDef::serialize(d, out),
            Self::AIScratchpadDef(d) => AIScratchpadDef::serialize(d, out),
            Self::AnimatingObjectDef(d) => AnimatingObjectDef::serialize(d, out),
            Self::AppearanceDef(d) => AppearanceDef::serialize(d, out),
            Self::AreaOfEffectAttackDef(d) => AreaOfEffectAttackDef::serialize(d, out),
            Self::ArmourDef(d) => ArmourDef::serialize(d, out),
            Self::AttackPatternDef(d) => AttackPatternDef::serialize(d, out),
            Self::AugmentationDef(d) => AugmentationDef::serialize(d, out),
            Self::BalverineBattleDef(d) => BalverineBattleDef::serialize(d, out),
            Self::BedDef(d) => BedDef::serialize(d, out),
            Self::BettingDef(d) => BettingDef::serialize(d, out),
            Self::BoastingPodiumDef(d) => BoastingPodiumDef::serialize(d, out),
            Self::BonusItemDef(d) => BonusItemDef::serialize(d, out),
            Self::BossDef(d) => BossDef::serialize(d, out),
            Self::BrainDef(d) => BrainDef::serialize(d, out),
            Self::BriarRoseDef(d) => BriarRoseDef::serialize(d, out),
            Self::BuyHouseDef(d) => BuyHouseDef::serialize(d, out),
            Self::BuyableHouseDef(d) => BuyableHouseDef::serialize(d, out),
            Self::CameraCollisionDef(d) => CameraCollisionDef::serialize(d, out),
            Self::CameraManagerDef(d) => CameraManagerDef::serialize(d, out),
            Self::CameraManagerSetDef(d) => CameraManagerSetDef::serialize(d, out),
            Self::CameraModeDef(d) => CameraModeDef::serialize(d, out),
            Self::CarriedReadableDef(d) => CarriedReadableDef::serialize(d, out),
            Self::CarrySlotDef(d) => CarrySlotDef::serialize(d, out),
            Self::CarryableDef(d) => CarryableDef::serialize(d, out),
            Self::CarryingDef(d) => CarryingDef::serialize(d, out),
            Self::ChestDef(d) => ChestDef::serialize(d, out),
            Self::ClockDef(d) => ClockDef::serialize(d, out),
            Self::CoinGameObstacleDef(d) => CoinGameObstacleDef::serialize(d, out),
            Self::CombatAbilityAttackBase(d) => CombatAbilityAttackBase::serialize(d, out),
            Self::CombatAbilityBlockDefBase(d) => CombatAbilityBlockDefBase::serialize(d, out),
            Self::CombatAbilityStrafeDef(d) => CombatAbilityStrafeDef::serialize(d, out),
            Self::CombatAbilityUseProjectileWeaponDef(d) => CombatAbilityUseProjectileWeaponDef::serialize(d, out),
            Self::CombatDialogueDef(d) => CombatDialogueDef::serialize(d, out),
            Self::CombatSequenceDef(d) => CombatSequenceDef::serialize(d, out),
            Self::CombatTypeDef(d) => CombatTypeDef::serialize(d, out),
            Self::ContainerRewardHeroDef(d) => ContainerRewardHeroDef::serialize(d, out),
            Self::ContextSensitiveItemDef(d) => ContextSensitiveItemDef::serialize(d, out),
            Self::CoopSpiritDef(d) => CoopSpiritDef::serialize(d, out),
            Self::CrateStackDef(d) => CrateStackDef::serialize(d, out),
            Self::CreatureAbilityDef(d) => CreatureAbilityDef::serialize(d, out),
            Self::CreatureDef(d) => CreatureDef::serialize(d, out),
            Self::CreatureGenerationFamilyDef(d) => CreatureGenerationFamilyDef::serialize(d, out),
            Self::CreatureGeneratorDef(d) => CreatureGeneratorDef::serialize(d, out),
            Self::CreatureModeDef(d) => CreatureModeDef::serialize(d, out),
            Self::CreatureNavigationDef(d) => CreatureNavigationDef::serialize(d, out),
            Self::CreatureStatsDef(d) => CreatureStatsDef::serialize(d, out),
            Self::CutsceneDef(d) => CutsceneDef::serialize(d, out),
            Self::DecapitationDef(d) => DecapitationDef::serialize(d, out),
            Self::DoorDef(d) => DoorDef::serialize(d, out),
            Self::DragonActionHoverDef(d) => DragonActionHoverDef::serialize(d, out),
            Self::DragonActionNapalmDef(d) => DragonActionNapalmDef::serialize(d, out),
            Self::DragonActionSwoopDef(d) => DragonActionSwoopDef::serialize(d, out),
            Self::DrunkennessDef(d) => DrunkennessDef::serialize(d, out),
            Self::EnemyDef(d) => EnemyDef::serialize(d, out),
            Self::EngineLocalDetailGeneratorDef(d) => EngineLocalDetailGeneratorDef::serialize(d, out),
            Self::EngineThemeDef(d) => EngineThemeDef::serialize(d, out),
            Self::EngineThemeGroupDef(d) => EngineThemeGroupDef::serialize(d, out),
            Self::EntitySoundDef(d) => EntitySoundDef::serialize(d, out),
            Self::ExperienceDef(d) => ExperienceDef::serialize(d, out),
            Self::ExplodingObjectDef(d) => ExplodingObjectDef::serialize(d, out),
            Self::ExplosionDef(d) => ExplosionDef::serialize(d, out),
            Self::ExplosiveTrailDef(d) => ExplosiveTrailDef::serialize(d, out),
            Self::ExpressionDef(d) => ExpressionDef::serialize(d, out),
            Self::ExpressionSubDef(d) => ExpressionSubDef::serialize(d, out),
            Self::FactionDef(d) => FactionDef::serialize(d, out),
            Self::FireballSpellLevelDef(d) => FireballSpellLevelDef::serialize(d, out),
            Self::FireheartMinigameDef(d) => FireheartMinigameDef::serialize(d, out),
            Self::FishDef(d) => FishDef::serialize(d, out),
            Self::FishingDef(d) => FishingDef::serialize(d, out),
            Self::FishingRodDef(d) => FishingRodDef::serialize(d, out),
            Self::FlammableDef(d) => FlammableDef::serialize(d, out),
            Self::GiftDef(d) => GiftDef::serialize(d, out),
            Self::GoldDef(d) => GoldDef::serialize(d, out),
            Self::GuardDef(d) => GuardDef::serialize(d, out),
            Self::GuildMasterDef(d) => GuildMasterDef::serialize(d, out),
            Self::HairCardDef(d) => HairCardDef::serialize(d, out),
            Self::HasNameDef(d) => HasNameDef::serialize(d, out),
            Self::HeroAbilityDef(d) => HeroAbilityDef::serialize(d, out),
            Self::HeroCentreDef(d) => HeroCentreDef::serialize(d, out),
            Self::HeroCombatDef(d) => HeroCombatDef::serialize(d, out),
            Self::HeroDef(d) => HeroDef::serialize(d, out),
            Self::HeroExperienceDef(d) => HeroExperienceDef::serialize(d, out),
            Self::HeroMarriageDef(d) => HeroMarriageDef::serialize(d, out),
            Self::HeroMorphDef(d) => HeroMorphDef::serialize(d, out),
            Self::HeroPostcardGeneratorDef(d) => HeroPostcardGeneratorDef::serialize(d, out),
            Self::HeroSpecialMovementDef(d) => HeroSpecialMovementDef::serialize(d, out),
            Self::HeroStatsDef(d) => HeroStatsDef::serialize(d, out),
            Self::HeroSuitDef(d) => HeroSuitDef::serialize(d, out),
            Self::HeroTitleDef(d) => HeroTitleDef::serialize(d, out),
            Self::HighlightItemDef(d) => HighlightItemDef::serialize(d, out),
            Self::HitLocationDef(d) => HitLocationDef::serialize(d, out),
            Self::HitLocationsDef(d) => HitLocationsDef::serialize(d, out),
            Self::IdleSchedulerDef(d) => IdleSchedulerDef::serialize(d, out),
            Self::InterestingToVillagersDef(d) => InterestingToVillagersDef::serialize(d, out),
            Self::InventoryCategoryDef(d) => InventoryCategoryDef::serialize(d, out),
            Self::InventoryDef(d) => InventoryDef::serialize(d, out),
            Self::InventoryItemDef(d) => InventoryItemDef::serialize(d, out),
            Self::JackDragonDef(d) => JackDragonDef::serialize(d, out),
            Self::JackOfBladesBattleDef(d) => JackOfBladesBattleDef::serialize(d, out),
            Self::KickableDef(d) => KickableDef::serialize(d, out),
            Self::KrakenDef(d) => KrakenDef::serialize(d, out),
            Self::KrakenTentacleDef(d) => KrakenTentacleDef::serialize(d, out),
            Self::LightDef(d) => LightDef::serialize(d, out),
            Self::LightningDef(d) => LightningDef::serialize(d, out),
            Self::LightningOrbDef(d) => LightningOrbDef::serialize(d, out),
            Self::LookDef(d) => LookDef::serialize(d, out),
            Self::MaterialDef(d) => MaterialDef::serialize(d, out),
            Self::MazeBattleDef(d) => MazeBattleDef::serialize(d, out),
            Self::MeleeCombatAbilityDef(d) => MeleeCombatAbilityDef::serialize(d, out),
            Self::MeleeCombatKnockdownEffects(d) => MeleeCombatKnockdownEffects::serialize(d, out),
            Self::MessageEventDef(d) => MessageEventDef::serialize(d, out),
            Self::MultiStaticMeshDef(d) => MultiStaticMeshDef::serialize(d, out),
            Self::NymphDef(d) => NymphDef::serialize(d, out),
            Self::ObjectAugmentationsDef(d) => ObjectAugmentationsDef::serialize(d, out),
            Self::ObjectFamilyDef(d) => ObjectFamilyDef::serialize(d, out),
            Self::OccupiableDef(d) => OccupiableDef::serialize(d, out),
            Self::OpinionDeedEffectsDef(d) => OpinionDeedEffectsDef::serialize(d, out),
            Self::OpinionDeedMaskDef(d) => OpinionDeedMaskDef::serialize(d, out),
            Self::OpinionOfHeroDef(d) => OpinionOfHeroDef::serialize(d, out),
            Self::OpinionPersonalityDef(d) => OpinionPersonalityDef::serialize(d, out),
            Self::OpinionReactionManagerDef(d) => OpinionReactionManagerDef::serialize(d, out),
            Self::OpinionReactionMaskDef(d) => OpinionReactionMaskDef::serialize(d, out),
            Self::OpinionSourceDef(d) => OpinionSourceDef::serialize(d, out),
            Self::OracleMinigameDef(d) => OracleMinigameDef::serialize(d, out),
            Self::OverheadDisplayDef(d) => OverheadDisplayDef::serialize(d, out),
            Self::ParticleAttacherDef(d) => ParticleAttacherDef::serialize(d, out),
            Self::PerceivedThingDef(d) => PerceivedThingDef::serialize(d, out),
            Self::PhysicsDef(d) => PhysicsDef::serialize(d, out),
            Self::PlayerDef(d) => PlayerDef::serialize(d, out),
            Self::PlayerGuiDef(d) => PlayerGuiDef::serialize(d, out),
            Self::PlayerInventoryDef(d) => PlayerInventoryDef::serialize(d, out),
            Self::QuestCardDef(d) => QuestCardDef::serialize(d, out),
            Self::ReadableDef(d) => ReadableDef::serialize(d, out),
            Self::RegionDef(d) => RegionDef::serialize(d, out),
            Self::RegionScriptDef(d) => RegionScriptDef::serialize(d, out),
            Self::ResurrectionItemDef(d) => ResurrectionItemDef::serialize(d, out),
            Self::RumbleDef(d) => RumbleDef::serialize(d, out),
            Self::ScorpionKingBattleDef(d) => ScorpionKingBattleDef::serialize(d, out),
            Self::ScriptDef(d) => ScriptDef::serialize(d, out),
            Self::ShipDef(d) => ShipDef::serialize(d, out),
            Self::SimBuildingDef(d) => SimBuildingDef::serialize(d, out),
            Self::SimVoicesDef(d) => SimVoicesDef::serialize(d, out),
            Self::SkeletalMorphDef(d) => SkeletalMorphDef::serialize(d, out),
            Self::SkyDef(d) => SkyDef::serialize(d, out),
            Self::SmashableDef(d) => SmashableDef::serialize(d, out),
            Self::SmokeGeneratorDef(d) => SmokeGeneratorDef::serialize(d, out),
            Self::SnowTrollDef(d) => SnowTrollDef::serialize(d, out),
            Self::SoundAtmospheresDef(d) => SoundAtmospheresDef::serialize(d, out),
            Self::SoundDef(d) => SoundDef::serialize(d, out),
            Self::SoundThemeDef(d) => SoundThemeDef::serialize(d, out),
            Self::SpecialAbilitiesAssassinRushDef(d) => SpecialAbilitiesAssassinRushDef::serialize(d, out),
            Self::SpecialAbilitiesBattleChargeDef(d) => SpecialAbilitiesBattleChargeDef::serialize(d, out),
            Self::SpecialAbilitiesBerserkDef(d) => SpecialAbilitiesBerserkDef::serialize(d, out),
            Self::SpecialAbilitiesBulletTimeDef(d) => SpecialAbilitiesBulletTimeDef::serialize(d, out),
            Self::SpecialAbilitiesBurntEffectDef(d) => SpecialAbilitiesBurntEffectDef::serialize(d, out),
            Self::SpecialAbilitiesCreatureTintDef(d) => SpecialAbilitiesCreatureTintDef::serialize(d, out),
            Self::SpecialAbilitiesDrainLifeDef(d) => SpecialAbilitiesDrainLifeDef::serialize(d, out),
            Self::SpecialAbilitiesDrunkennessDef(d) => SpecialAbilitiesDrunkennessDef::serialize(d, out),
            Self::SpecialAbilitiesElectrocutedEffectDef(d) => SpecialAbilitiesElectrocutedEffectDef::serialize(d, out),
            Self::SpecialAbilitiesEnflameDef(d) => SpecialAbilitiesEnflameDef::serialize(d, out),
            Self::SpecialAbilitiesFireballSpellDef(d) => SpecialAbilitiesFireballSpellDef::serialize(d, out),
            Self::SpecialAbilitiesForcePushDataDef(d) => SpecialAbilitiesForcePushDataDef::serialize(d, out),
            Self::SpecialAbilitiesForcePushDef(d) => SpecialAbilitiesForcePushDef::serialize(d, out),
            Self::SpecialAbilitiesGhostSwordDef(d) => SpecialAbilitiesGhostSwordDef::serialize(d, out),
            Self::SpecialAbilitiesHealLifeDef(d) => SpecialAbilitiesHealLifeDef::serialize(d, out),
            Self::SpecialAbilitiesLightningSpellDef(d) => SpecialAbilitiesLightningSpellDef::serialize(d, out),
            Self::SpecialAbilitiesMultiArrowDef(d) => SpecialAbilitiesMultiArrowDef::serialize(d, out),
            Self::SpecialAbilitiesMultiStrikeDef(d) => SpecialAbilitiesMultiStrikeDef::serialize(d, out),
            Self::SpecialAbilitiesPhysicalShieldDef(d) => SpecialAbilitiesPhysicalShieldDef::serialize(d, out),
            Self::SpecialAbilitiesSummonSpellDef(d) => SpecialAbilitiesSummonSpellDef::serialize(d, out),
            Self::SpecialAbilitiesThunderLightningStormDef(d) => SpecialAbilitiesThunderLightningStormDef::serialize(d, out),
            Self::SpecialAbilitiesTurncoatSpellDef(d) => SpecialAbilitiesTurncoatSpellDef::serialize(d, out),
            Self::SpecialAbilitiesUnholyPowerDef(d) => SpecialAbilitiesUnholyPowerDef::serialize(d, out),
            Self::SpecialEffectsDef(d) => SpecialEffectsDef::serialize(d, out),
            Self::SpotLightDef(d) => SpotLightDef::serialize(d, out),
            Self::StealthDef(d) => StealthDef::serialize(d, out),
            Self::StockItemDef(d) => StockItemDef::serialize(d, out),
            Self::SummonDef(d) => SummonDef::serialize(d, out),
            Self::SummonableCreatureDef(d) => SummonableCreatureDef::serialize(d, out),
            Self::SummonerDef(d) => SummonerDef::serialize(d, out),
            Self::TCVolumeContainmentTrackerDef(d) => TCVolumeContainmentTrackerDef::serialize(d, out),
            Self::TargetingDef(d) => TargetingDef::serialize(d, out),
            Self::TattooDef(d) => TattooDef::serialize(d, out),
            Self::TavernDef(d) => TavernDef::serialize(d, out),
            Self::TavernGameCardBaseDef(d) => TavernGameCardBaseDef::serialize(d, out),
            Self::TavernGameCoinBaseDef(d) => TavernGameCoinBaseDef::serialize(d, out),
            Self::TavernGameCoinGolfDef(d) => TavernGameCoinGolfDef::serialize(d, out),
            Self::TavernGameDef(d) => TavernGameDef::serialize(d, out),
            Self::TavernGameShoveHaPennyDef(d) => TavernGameShoveHaPennyDef::serialize(d, out),
            Self::TavernGameSpotTheAdditionDef(d) => TavernGameSpotTheAdditionDef::serialize(d, out),
            Self::TavernTableDef(d) => TavernTableDef::serialize(d, out),
            Self::TeleporterDef(d) => TeleporterDef::serialize(d, out),
            Self::TextureReplacementDef(d) => TextureReplacementDef::serialize(d, out),
            Self::ThingBaseDef(d) => ThingBaseDef::serialize(d, out),
            Self::ThingBuildingDef(d) => ThingBuildingDef::serialize(d, out),
            Self::ThingCreatureDef(d) => ThingCreatureDef::serialize(d, out),
            Self::ThingDrainLifeShotDef(d) => ThingDrainLifeShotDef::serialize(d, out),
            Self::ThingHolySiteDef(d) => ThingHolySiteDef::serialize(d, out),
            Self::ThingMarkerDef(d) => ThingMarkerDef::serialize(d, out),
            Self::ThingMultiArrowShotDef(d) => ThingMultiArrowShotDef::serialize(d, out),
            Self::ThingNoiseDef(d) => ThingNoiseDef::serialize(d, out),
            Self::ThingObjectDef(d) => ThingObjectDef::serialize(d, out),
            Self::ThingPhysicalSwitchDef(d) => ThingPhysicalSwitchDef::serialize(d, out),
            Self::ThingShotDef(d) => ThingShotDef::serialize(d, out),
            Self::ThingSwitchDef(d) => ThingSwitchDef::serialize(d, out),
            Self::ThingVillageDef(d) => ThingVillageDef::serialize(d, out),
            Self::ThunderBattleDef(d) => ThunderBattleDef::serialize(d, out),
            Self::TimeAppearanceFadeDef(d) => TimeAppearanceFadeDef::serialize(d, out),
            Self::TrapDef(d) => TrapDef::serialize(d, out),
            Self::TrollBattleDef(d) => TrollBattleDef::serialize(d, out),
            Self::TrophyDef(d) => TrophyDef::serialize(d, out),
            Self::TurncoatDef(d) => TurncoatDef::serialize(d, out),
            Self::UILocaleGraphicsDef(d) => UILocaleGraphicsDef::serialize(d, out),
            Self::UiMiscThingsDef(d) => UiMiscThingsDef::serialize(d, out),
            Self::VillageDef(d) => VillageDef::serialize(d, out),
            Self::VillageMemberDef(d) => VillageMemberDef::serialize(d, out),
            Self::VillagePeopleDef(d) => VillagePeopleDef::serialize(d, out),
            Self::VillagerInteractionsDef(d) => VillagerInteractionsDef::serialize(d, out),
            Self::WallMountEffectsDef(d) => WallMountEffectsDef::serialize(d, out),
            Self::WaspQueenBattleDef(d) => WaspQueenBattleDef::serialize(d, out),
            Self::WeaponDef(d) => WeaponDef::serialize(d, out),
            Self::WhisperBattleDef(d) => WhisperBattleDef::serialize(d, out),
            Self::WifeDef(d) => WifeDef::serialize(d, out),
            Self::WillResponseDef(d) => WillResponseDef::serialize(d, out),
            Self::DegradableDef(d) => DegradableDef::serialize(d, out),
            Self::AppearanceModifierDef(d) => AppearanceModifierDef::serialize(d, out),
            Self::ShopDef(d) => ShopDef::serialize(d, out),
            Self::ShopItemDef(d) => ShopItemDef::serialize(d, out),
            Self::ReplaceableMeshDef(d) => ReplaceableMeshDef::serialize(d, out),
            Self::GlobalDef(d) => GlobalDef::serialize(d, out),
            Self::PlayerMovementDef(d) => PlayerMovementDef::serialize(d, out),
        }
    }

    pub fn byte_size(&self) -> usize {
        match self {
            Self::AbilityDef(d) => AbilityDef::byte_size(d),
            Self::ActionUseDef(d) => ActionUseDef::byte_size(d),
            Self::ActivateQuestDef(d) => ActivateQuestDef::byte_size(d),
            Self::AICreatureWillPowerIndicatorDef(d) => AICreatureWillPowerIndicatorDef::byte_size(d),
            Self::AIScratchpadDef(d) => AIScratchpadDef::byte_size(d),
            Self::AnimatingObjectDef(d) => AnimatingObjectDef::byte_size(d),
            Self::AppearanceDef(d) => AppearanceDef::byte_size(d),
            Self::AreaOfEffectAttackDef(d) => AreaOfEffectAttackDef::byte_size(d),
            Self::ArmourDef(d) => ArmourDef::byte_size(d),
            Self::AttackPatternDef(d) => AttackPatternDef::byte_size(d),
            Self::AugmentationDef(d) => AugmentationDef::byte_size(d),
            Self::BalverineBattleDef(d) => BalverineBattleDef::byte_size(d),
            Self::BedDef(d) => BedDef::byte_size(d),
            Self::BettingDef(d) => BettingDef::byte_size(d),
            Self::BoastingPodiumDef(d) => BoastingPodiumDef::byte_size(d),
            Self::BonusItemDef(d) => BonusItemDef::byte_size(d),
            Self::BossDef(d) => BossDef::byte_size(d),
            Self::BrainDef(d) => BrainDef::byte_size(d),
            Self::BriarRoseDef(d) => BriarRoseDef::byte_size(d),
            Self::BuyHouseDef(d) => BuyHouseDef::byte_size(d),
            Self::BuyableHouseDef(d) => BuyableHouseDef::byte_size(d),
            Self::CameraCollisionDef(d) => CameraCollisionDef::byte_size(d),
            Self::CameraManagerDef(d) => CameraManagerDef::byte_size(d),
            Self::CameraManagerSetDef(d) => CameraManagerSetDef::byte_size(d),
            Self::CameraModeDef(d) => CameraModeDef::byte_size(d),
            Self::CarriedReadableDef(d) => CarriedReadableDef::byte_size(d),
            Self::CarrySlotDef(d) => CarrySlotDef::byte_size(d),
            Self::CarryableDef(d) => CarryableDef::byte_size(d),
            Self::CarryingDef(d) => CarryingDef::byte_size(d),
            Self::ChestDef(d) => ChestDef::byte_size(d),
            Self::ClockDef(d) => ClockDef::byte_size(d),
            Self::CoinGameObstacleDef(d) => CoinGameObstacleDef::byte_size(d),
            Self::CombatAbilityAttackBase(d) => CombatAbilityAttackBase::byte_size(d),
            Self::CombatAbilityBlockDefBase(d) => CombatAbilityBlockDefBase::byte_size(d),
            Self::CombatAbilityStrafeDef(d) => CombatAbilityStrafeDef::byte_size(d),
            Self::CombatAbilityUseProjectileWeaponDef(d) => CombatAbilityUseProjectileWeaponDef::byte_size(d),
            Self::CombatDialogueDef(d) => CombatDialogueDef::byte_size(d),
            Self::CombatSequenceDef(d) => CombatSequenceDef::byte_size(d),
            Self::CombatTypeDef(d) => CombatTypeDef::byte_size(d),
            Self::ContainerRewardHeroDef(d) => ContainerRewardHeroDef::byte_size(d),
            Self::ContextSensitiveItemDef(d) => ContextSensitiveItemDef::byte_size(d),
            Self::CoopSpiritDef(d) => CoopSpiritDef::byte_size(d),
            Self::CrateStackDef(d) => CrateStackDef::byte_size(d),
            Self::CreatureAbilityDef(d) => CreatureAbilityDef::byte_size(d),
            Self::CreatureDef(d) => CreatureDef::byte_size(d),
            Self::CreatureGenerationFamilyDef(d) => CreatureGenerationFamilyDef::byte_size(d),
            Self::CreatureGeneratorDef(d) => CreatureGeneratorDef::byte_size(d),
            Self::CreatureModeDef(d) => CreatureModeDef::byte_size(d),
            Self::CreatureNavigationDef(d) => CreatureNavigationDef::byte_size(d),
            Self::CreatureStatsDef(d) => CreatureStatsDef::byte_size(d),
            Self::CutsceneDef(d) => CutsceneDef::byte_size(d),
            Self::DecapitationDef(d) => DecapitationDef::byte_size(d),
            Self::DoorDef(d) => DoorDef::byte_size(d),
            Self::DragonActionHoverDef(d) => DragonActionHoverDef::byte_size(d),
            Self::DragonActionNapalmDef(d) => DragonActionNapalmDef::byte_size(d),
            Self::DragonActionSwoopDef(d) => DragonActionSwoopDef::byte_size(d),
            Self::DrunkennessDef(d) => DrunkennessDef::byte_size(d),
            Self::EnemyDef(d) => EnemyDef::byte_size(d),
            Self::EngineLocalDetailGeneratorDef(d) => EngineLocalDetailGeneratorDef::byte_size(d),
            Self::EngineThemeDef(d) => EngineThemeDef::byte_size(d),
            Self::EngineThemeGroupDef(d) => EngineThemeGroupDef::byte_size(d),
            Self::EntitySoundDef(d) => EntitySoundDef::byte_size(d),
            Self::ExperienceDef(d) => ExperienceDef::byte_size(d),
            Self::ExplodingObjectDef(d) => ExplodingObjectDef::byte_size(d),
            Self::ExplosionDef(d) => ExplosionDef::byte_size(d),
            Self::ExplosiveTrailDef(d) => ExplosiveTrailDef::byte_size(d),
            Self::ExpressionDef(d) => ExpressionDef::byte_size(d),
            Self::ExpressionSubDef(d) => ExpressionSubDef::byte_size(d),
            Self::FactionDef(d) => FactionDef::byte_size(d),
            Self::FireballSpellLevelDef(d) => FireballSpellLevelDef::byte_size(d),
            Self::FireheartMinigameDef(d) => FireheartMinigameDef::byte_size(d),
            Self::FishDef(d) => FishDef::byte_size(d),
            Self::FishingDef(d) => FishingDef::byte_size(d),
            Self::FishingRodDef(d) => FishingRodDef::byte_size(d),
            Self::FlammableDef(d) => FlammableDef::byte_size(d),
            Self::GiftDef(d) => GiftDef::byte_size(d),
            Self::GoldDef(d) => GoldDef::byte_size(d),
            Self::GuardDef(d) => GuardDef::byte_size(d),
            Self::GuildMasterDef(d) => GuildMasterDef::byte_size(d),
            Self::HairCardDef(d) => HairCardDef::byte_size(d),
            Self::HasNameDef(d) => HasNameDef::byte_size(d),
            Self::HeroAbilityDef(d) => HeroAbilityDef::byte_size(d),
            Self::HeroCentreDef(d) => HeroCentreDef::byte_size(d),
            Self::HeroCombatDef(d) => HeroCombatDef::byte_size(d),
            Self::HeroDef(d) => HeroDef::byte_size(d),
            Self::HeroExperienceDef(d) => HeroExperienceDef::byte_size(d),
            Self::HeroMarriageDef(d) => HeroMarriageDef::byte_size(d),
            Self::HeroMorphDef(d) => HeroMorphDef::byte_size(d),
            Self::HeroPostcardGeneratorDef(d) => HeroPostcardGeneratorDef::byte_size(d),
            Self::HeroSpecialMovementDef(d) => HeroSpecialMovementDef::byte_size(d),
            Self::HeroStatsDef(d) => HeroStatsDef::byte_size(d),
            Self::HeroSuitDef(d) => HeroSuitDef::byte_size(d),
            Self::HeroTitleDef(d) => HeroTitleDef::byte_size(d),
            Self::HighlightItemDef(d) => HighlightItemDef::byte_size(d),
            Self::HitLocationDef(d) => HitLocationDef::byte_size(d),
            Self::HitLocationsDef(d) => HitLocationsDef::byte_size(d),
            Self::IdleSchedulerDef(d) => IdleSchedulerDef::byte_size(d),
            Self::InterestingToVillagersDef(d) => InterestingToVillagersDef::byte_size(d),
            Self::InventoryCategoryDef(d) => InventoryCategoryDef::byte_size(d),
            Self::InventoryDef(d) => InventoryDef::byte_size(d),
            Self::InventoryItemDef(d) => InventoryItemDef::byte_size(d),
            Self::JackDragonDef(d) => JackDragonDef::byte_size(d),
            Self::JackOfBladesBattleDef(d) => JackOfBladesBattleDef::byte_size(d),
            Self::KickableDef(d) => KickableDef::byte_size(d),
            Self::KrakenDef(d) => KrakenDef::byte_size(d),
            Self::KrakenTentacleDef(d) => KrakenTentacleDef::byte_size(d),
            Self::LightDef(d) => LightDef::byte_size(d),
            Self::LightningDef(d) => LightningDef::byte_size(d),
            Self::LightningOrbDef(d) => LightningOrbDef::byte_size(d),
            Self::LookDef(d) => LookDef::byte_size(d),
            Self::MaterialDef(d) => MaterialDef::byte_size(d),
            Self::MazeBattleDef(d) => MazeBattleDef::byte_size(d),
            Self::MeleeCombatAbilityDef(d) => MeleeCombatAbilityDef::byte_size(d),
            Self::MeleeCombatKnockdownEffects(d) => MeleeCombatKnockdownEffects::byte_size(d),
            Self::MessageEventDef(d) => MessageEventDef::byte_size(d),
            Self::MultiStaticMeshDef(d) => MultiStaticMeshDef::byte_size(d),
            Self::NymphDef(d) => NymphDef::byte_size(d),
            Self::ObjectAugmentationsDef(d) => ObjectAugmentationsDef::byte_size(d),
            Self::ObjectFamilyDef(d) => ObjectFamilyDef::byte_size(d),
            Self::OccupiableDef(d) => OccupiableDef::byte_size(d),
            Self::OpinionDeedEffectsDef(d) => OpinionDeedEffectsDef::byte_size(d),
            Self::OpinionDeedMaskDef(d) => OpinionDeedMaskDef::byte_size(d),
            Self::OpinionOfHeroDef(d) => OpinionOfHeroDef::byte_size(d),
            Self::OpinionPersonalityDef(d) => OpinionPersonalityDef::byte_size(d),
            Self::OpinionReactionManagerDef(d) => OpinionReactionManagerDef::byte_size(d),
            Self::OpinionReactionMaskDef(d) => OpinionReactionMaskDef::byte_size(d),
            Self::OpinionSourceDef(d) => OpinionSourceDef::byte_size(d),
            Self::OracleMinigameDef(d) => OracleMinigameDef::byte_size(d),
            Self::OverheadDisplayDef(d) => OverheadDisplayDef::byte_size(d),
            Self::ParticleAttacherDef(d) => ParticleAttacherDef::byte_size(d),
            Self::PerceivedThingDef(d) => PerceivedThingDef::byte_size(d),
            Self::PhysicsDef(d) => PhysicsDef::byte_size(d),
            Self::PlayerDef(d) => PlayerDef::byte_size(d),
            Self::PlayerGuiDef(d) => PlayerGuiDef::byte_size(d),
            Self::PlayerInventoryDef(d) => PlayerInventoryDef::byte_size(d),
            Self::QuestCardDef(d) => QuestCardDef::byte_size(d),
            Self::ReadableDef(d) => ReadableDef::byte_size(d),
            Self::RegionDef(d) => RegionDef::byte_size(d),
            Self::RegionScriptDef(d) => RegionScriptDef::byte_size(d),
            Self::ResurrectionItemDef(d) => ResurrectionItemDef::byte_size(d),
            Self::RumbleDef(d) => RumbleDef::byte_size(d),
            Self::ScorpionKingBattleDef(d) => ScorpionKingBattleDef::byte_size(d),
            Self::ScriptDef(d) => ScriptDef::byte_size(d),
            Self::ShipDef(d) => ShipDef::byte_size(d),
            Self::SimBuildingDef(d) => SimBuildingDef::byte_size(d),
            Self::SimVoicesDef(d) => SimVoicesDef::byte_size(d),
            Self::SkeletalMorphDef(d) => SkeletalMorphDef::byte_size(d),
            Self::SkyDef(d) => SkyDef::byte_size(d),
            Self::SmashableDef(d) => SmashableDef::byte_size(d),
            Self::SmokeGeneratorDef(d) => SmokeGeneratorDef::byte_size(d),
            Self::SnowTrollDef(d) => SnowTrollDef::byte_size(d),
            Self::SoundAtmospheresDef(d) => SoundAtmospheresDef::byte_size(d),
            Self::SoundDef(d) => SoundDef::byte_size(d),
            Self::SoundThemeDef(d) => SoundThemeDef::byte_size(d),
            Self::SpecialAbilitiesAssassinRushDef(d) => SpecialAbilitiesAssassinRushDef::byte_size(d),
            Self::SpecialAbilitiesBattleChargeDef(d) => SpecialAbilitiesBattleChargeDef::byte_size(d),
            Self::SpecialAbilitiesBerserkDef(d) => SpecialAbilitiesBerserkDef::byte_size(d),
            Self::SpecialAbilitiesBulletTimeDef(d) => SpecialAbilitiesBulletTimeDef::byte_size(d),
            Self::SpecialAbilitiesBurntEffectDef(d) => SpecialAbilitiesBurntEffectDef::byte_size(d),
            Self::SpecialAbilitiesCreatureTintDef(d) => SpecialAbilitiesCreatureTintDef::byte_size(d),
            Self::SpecialAbilitiesDrainLifeDef(d) => SpecialAbilitiesDrainLifeDef::byte_size(d),
            Self::SpecialAbilitiesDrunkennessDef(d) => SpecialAbilitiesDrunkennessDef::byte_size(d),
            Self::SpecialAbilitiesElectrocutedEffectDef(d) => SpecialAbilitiesElectrocutedEffectDef::byte_size(d),
            Self::SpecialAbilitiesEnflameDef(d) => SpecialAbilitiesEnflameDef::byte_size(d),
            Self::SpecialAbilitiesFireballSpellDef(d) => SpecialAbilitiesFireballSpellDef::byte_size(d),
            Self::SpecialAbilitiesForcePushDataDef(d) => SpecialAbilitiesForcePushDataDef::byte_size(d),
            Self::SpecialAbilitiesForcePushDef(d) => SpecialAbilitiesForcePushDef::byte_size(d),
            Self::SpecialAbilitiesGhostSwordDef(d) => SpecialAbilitiesGhostSwordDef::byte_size(d),
            Self::SpecialAbilitiesHealLifeDef(d) => SpecialAbilitiesHealLifeDef::byte_size(d),
            Self::SpecialAbilitiesLightningSpellDef(d) => SpecialAbilitiesLightningSpellDef::byte_size(d),
            Self::SpecialAbilitiesMultiArrowDef(d) => SpecialAbilitiesMultiArrowDef::byte_size(d),
            Self::SpecialAbilitiesMultiStrikeDef(d) => SpecialAbilitiesMultiStrikeDef::byte_size(d),
            Self::SpecialAbilitiesPhysicalShieldDef(d) => SpecialAbilitiesPhysicalShieldDef::byte_size(d),
            Self::SpecialAbilitiesSummonSpellDef(d) => SpecialAbilitiesSummonSpellDef::byte_size(d),
            Self::SpecialAbilitiesThunderLightningStormDef(d) => SpecialAbilitiesThunderLightningStormDef::byte_size(d),
            Self::SpecialAbilitiesTurncoatSpellDef(d) => SpecialAbilitiesTurncoatSpellDef::byte_size(d),
            Self::SpecialAbilitiesUnholyPowerDef(d) => SpecialAbilitiesUnholyPowerDef::byte_size(d),
            Self::SpecialEffectsDef(d) => SpecialEffectsDef::byte_size(d),
            Self::SpotLightDef(d) => SpotLightDef::byte_size(d),
            Self::StealthDef(d) => StealthDef::byte_size(d),
            Self::StockItemDef(d) => StockItemDef::byte_size(d),
            Self::SummonDef(d) => SummonDef::byte_size(d),
            Self::SummonableCreatureDef(d) => SummonableCreatureDef::byte_size(d),
            Self::SummonerDef(d) => SummonerDef::byte_size(d),
            Self::TCVolumeContainmentTrackerDef(d) => TCVolumeContainmentTrackerDef::byte_size(d),
            Self::TargetingDef(d) => TargetingDef::byte_size(d),
            Self::TattooDef(d) => TattooDef::byte_size(d),
            Self::TavernDef(d) => TavernDef::byte_size(d),
            Self::TavernGameCardBaseDef(d) => TavernGameCardBaseDef::byte_size(d),
            Self::TavernGameCoinBaseDef(d) => TavernGameCoinBaseDef::byte_size(d),
            Self::TavernGameCoinGolfDef(d) => TavernGameCoinGolfDef::byte_size(d),
            Self::TavernGameDef(d) => TavernGameDef::byte_size(d),
            Self::TavernGameShoveHaPennyDef(d) => TavernGameShoveHaPennyDef::byte_size(d),
            Self::TavernGameSpotTheAdditionDef(d) => TavernGameSpotTheAdditionDef::byte_size(d),
            Self::TavernTableDef(d) => TavernTableDef::byte_size(d),
            Self::TeleporterDef(d) => TeleporterDef::byte_size(d),
            Self::TextureReplacementDef(d) => TextureReplacementDef::byte_size(d),
            Self::ThingBaseDef(d) => ThingBaseDef::byte_size(d),
            Self::ThingBuildingDef(d) => ThingBuildingDef::byte_size(d),
            Self::ThingCreatureDef(d) => ThingCreatureDef::byte_size(d),
            Self::ThingDrainLifeShotDef(d) => ThingDrainLifeShotDef::byte_size(d),
            Self::ThingHolySiteDef(d) => ThingHolySiteDef::byte_size(d),
            Self::ThingMarkerDef(d) => ThingMarkerDef::byte_size(d),
            Self::ThingMultiArrowShotDef(d) => ThingMultiArrowShotDef::byte_size(d),
            Self::ThingNoiseDef(d) => ThingNoiseDef::byte_size(d),
            Self::ThingObjectDef(d) => ThingObjectDef::byte_size(d),
            Self::ThingPhysicalSwitchDef(d) => ThingPhysicalSwitchDef::byte_size(d),
            Self::ThingShotDef(d) => ThingShotDef::byte_size(d),
            Self::ThingSwitchDef(d) => ThingSwitchDef::byte_size(d),
            Self::ThingVillageDef(d) => ThingVillageDef::byte_size(d),
            Self::ThunderBattleDef(d) => ThunderBattleDef::byte_size(d),
            Self::TimeAppearanceFadeDef(d) => TimeAppearanceFadeDef::byte_size(d),
            Self::TrapDef(d) => TrapDef::byte_size(d),
            Self::TrollBattleDef(d) => TrollBattleDef::byte_size(d),
            Self::TrophyDef(d) => TrophyDef::byte_size(d),
            Self::TurncoatDef(d) => TurncoatDef::byte_size(d),
            Self::UILocaleGraphicsDef(d) => UILocaleGraphicsDef::byte_size(d),
            Self::UiMiscThingsDef(d) => UiMiscThingsDef::byte_size(d),
            Self::VillageDef(d) => VillageDef::byte_size(d),
            Self::VillageMemberDef(d) => VillageMemberDef::byte_size(d),
            Self::VillagePeopleDef(d) => VillagePeopleDef::byte_size(d),
            Self::VillagerInteractionsDef(d) => VillagerInteractionsDef::byte_size(d),
            Self::WallMountEffectsDef(d) => WallMountEffectsDef::byte_size(d),
            Self::WaspQueenBattleDef(d) => WaspQueenBattleDef::byte_size(d),
            Self::WeaponDef(d) => WeaponDef::byte_size(d),
            Self::WhisperBattleDef(d) => WhisperBattleDef::byte_size(d),
            Self::WifeDef(d) => WifeDef::byte_size(d),
            Self::WillResponseDef(d) => WillResponseDef::byte_size(d),
            Self::DegradableDef(d) => DegradableDef::byte_size(d),
            Self::ReplaceableMeshDef(d) => ReplaceableMeshDef::byte_size(d),
            Self::GlobalDef(d) => GlobalDef::byte_size(d),
            Self::PlayerMovementDef(d) => PlayerMovementDef::byte_size(d),
            Self::AppearanceModifierDef(d) => AppearanceModifierDef::byte_size(d),
            Self::ShopDef(d) => ShopDef::byte_size(d),
            Self::ShopItemDef(d) => ShopItemDef::byte_size(d),
        }
    }
}

// ── Sub-def table ──────────────────────────────────────
/// Whether entries of the named def type carry a sub-def table (`u16` count +
/// 12-byte records) between the entry preamble and the field controls.
/// Presence is a per-type property: these are the def classes deriving from
/// the sub-def bases (`CSubDefClassBase`/`CParentDefClassBase`), verified
/// against all three retail bins.
pub fn def_name_has_subdef_table(name: &str) -> bool {
    matches!(
        name,
        "ARMOUR"
            | "ATTACK_PATTERN"
            | "BRAIN"
            | "BUILDING"
            | "CAMERA_MANAGER"
            | "CAMERA_MANAGER_SET"
            | "CAMERA_MODE"
            | "CAreaOfEffectAttackDef"
            | "CBalverineBattleDef"
            | "CCutsceneDef"
            | "CHeroPostcardGeneratorDef"
            | "CIdleSchedulerDef"
            | "CJackOfBladesBattleDef"
            | "CMazeBattleDef"
            | "COMBAT_DIALOGUE_DEF"
            | "COMBAT_SEQUENCE"
            | "COMBAT_TYPE"
            | "CONFIG_OPTIONS_DEFAULTS_DEF"
            | "CONTROL_SCHEME"
            | "CREATURE"
            | "CREATURE_ABILITY"
            | "CREATURE_GENERATION_FAMILY"
            | "CRegionScriptDef"
            | "CScorpionKingBattleDef"
            | "CScriptDef"
            | "CThunderBattleDef"
            | "CTrollBattleDef"
            | "CWaspQueenBattleDef"
            | "CWhisperBattleDef"
            | "ENGINE"
            | "ENGINE_THEME"
            | "ENGINE_THEME_GROUP"
            | "ENGINE_VIDEO_OPTIONS"
            | "ENVIRONMENT"
            | "ENVIRONMENT_THEME_DAY"
            | "EXPRESSION"
            | "FACTION"
            | "FRONT_END"
            | "GLOBAL"
            | "HERO_ABILITY"
            | "HERO_COMBAT"
            | "HERO_MELEE_COMBAT_ABILITY"
            | "HERO_STATS"
            | "HIT_LOCATION"
            | "HOLY_SITE"
            | "INVENTORY_CATEGORY"
            | "INVENTORY_TYPE"
            | "LIGHTNING"
            | "LOCAL_DETAIL_GENERATOR"
            | "MARKER"
            | "MATERIAL"
            | "MELEE_COMBAT_KNOCKDOWN_EFFECTS"
            | "MESSAGE_EVENT"
            | "NOISE"
            | "OBJECT"
            | "OBJECT_FAMILY"
            | "OPINION_DEED_EFFECTS"
            | "OPINION_DEED_MASK"
            | "OPINION_PERSONALITY"
            | "OPINION_REACTION_MANAGER"
            | "OPINION_REACTION_MASK"
            | "OPINION_SOURCE"
            | "PHYSICAL_SWITCH"
            | "PLAYER"
            | "PLAYER_GUI"
            | "PLAYER_INVENTORY"
            | "PLAYER_MOVEMENT"
            | "REGION"
            | "SHOT"
            | "SIM_BUILDING"
            | "SIM_VOICES"
            | "SKY"
            | "SOUND_SETUP"
            | "SOUND_THEME"
            | "SPECIAL_ABILITIES_ASSASSIN_RUSH_DEF"
            | "SPECIAL_ABILITIES_BATTLE_CHARGE_DEF"
            | "SPECIAL_ABILITIES_BERSERK_DEF"
            | "SPECIAL_ABILITIES_BULLET_TIME_DEF"
            | "SPECIAL_ABILITIES_BURNT_EFFECT_DEF"
            | "SPECIAL_ABILITIES_CREATURE_TINT_DEF"
            | "SPECIAL_ABILITIES_DIVINE_WRATH_DEF"
            | "SPECIAL_ABILITIES_DRAIN_LIFE_DEF"
            | "SPECIAL_ABILITIES_DRUNKENNESS_DEF"
            | "SPECIAL_ABILITIES_ELECTROCUTED_EFFECT_DEF"
            | "SPECIAL_ABILITIES_ENFLAME_DEF"
            | "SPECIAL_ABILITIES_FIREBALL_SPELL_DEF"
            | "SPECIAL_ABILITIES_FORCE_PUSH_DEF"
            | "SPECIAL_ABILITIES_GHOST_SWORD_DEF"
            | "SPECIAL_ABILITIES_HEAL_LIFE_DEF"
            | "SPECIAL_ABILITIES_LIGHTNING_SPELL_DEF"
            | "SPECIAL_ABILITIES_MULTI_ARROW_DEF"
            | "SPECIAL_ABILITIES_MULTI_STRIKE_DEF"
            | "SPECIAL_ABILITIES_PHYSICAL_SHIELD_DEF"
            | "SPECIAL_ABILITIES_SUMMON_SPELL_DEF"
            | "SPECIAL_ABILITIES_THUNDER_LIGHTNING_STORM_DEF"
            | "SPECIAL_ABILITIES_TURNCOAT_SPELL_DEF"
            | "SPECIAL_ABILITIES_UNHOLY_POWER_DEF"
            | "SWITCH"
            | "THING"
            | "THING_GROUP"
            | "UI"
            | "UI_ICONS_DEF"
            | "UI_LOCALE_GRAPHICS_DEF"
            | "UI_MISC_THINGS_DEF"
            | "VILLAGE"
            | "VILLAGER_INTERACTION"
    )
}

// ── Dispatch ───────────────────────────────────────────

/// Parse a game def body by type name. Returns `Ok(None)` when `name` isn't a
/// known game def type (callers fall back to raw bytes); returns `Err` when
/// the type is known but its body doesn't match the modeled layout — callers
/// may then retry past an instance prefix rather than losing data.
pub fn parse_game_def(
    name: &str,
    cur: &mut &[u8],
) -> Result<Option<DefBody>, ParseControlError> {
    Ok(Some(match name {
        "CAbilityDef" => DefBody::Game(GameBody::AbilityDef(AbilityDef::parse(cur)?)),
        "CActionUseDef" => DefBody::Game(GameBody::ActionUseDef(ActionUseDef::parse(cur)?)),
        "CActivateQuestDef" => DefBody::Game(GameBody::ActivateQuestDef(ActivateQuestDef::parse(cur)?)),
        "CAICreatureWillPowerIndicatorDef" => DefBody::Game(GameBody::AICreatureWillPowerIndicatorDef(AICreatureWillPowerIndicatorDef::parse(cur)?)),
        "CAIScratchpadDef" => DefBody::Game(GameBody::AIScratchpadDef(AIScratchpadDef::parse(cur)?)),
        "CAnimatingObjectDef" => DefBody::Game(GameBody::AnimatingObjectDef(AnimatingObjectDef::parse(cur)?)),
        "CAppearanceDef" => DefBody::Game(GameBody::AppearanceDef(AppearanceDef::parse(cur)?)),
        "CAreaOfEffectAttackDef" => DefBody::Game(GameBody::AreaOfEffectAttackDef(AreaOfEffectAttackDef::parse(cur)?)),
        "ARMOUR" => DefBody::Game(GameBody::ArmourDef(ArmourDef::parse(cur)?)),
        "ATTACK_PATTERN" => DefBody::Game(GameBody::AttackPatternDef(AttackPatternDef::parse(cur)?)),
        "CAugmentationDef" => DefBody::Game(GameBody::AugmentationDef(AugmentationDef::parse(cur)?)),
        "CBalverineBattleDef" => DefBody::Game(GameBody::BalverineBattleDef(BalverineBattleDef::parse(cur)?)),
        "CBedDef" => DefBody::Game(GameBody::BedDef(BedDef::parse(cur)?)),
        "CBettingDef" => DefBody::Game(GameBody::BettingDef(BettingDef::parse(cur)?)),
        "CBoastingPodiumDef" => DefBody::Game(GameBody::BoastingPodiumDef(BoastingPodiumDef::parse(cur)?)),
        "CBonusItemDef" => DefBody::Game(GameBody::BonusItemDef(BonusItemDef::parse(cur)?)),
        "CBossDef" => DefBody::Game(GameBody::BossDef(BossDef::parse(cur)?)),
        "BRAIN" => DefBody::Game(GameBody::BrainDef(BrainDef::parse(cur)?)),
        "CBriarRoseDef" => DefBody::Game(GameBody::BriarRoseDef(BriarRoseDef::parse(cur)?)),
        "CBuyHouseDef" => DefBody::Game(GameBody::BuyHouseDef(BuyHouseDef::parse(cur)?)),
        "CBuyableHouseDef" => DefBody::Game(GameBody::BuyableHouseDef(BuyableHouseDef::parse(cur)?)),
        "CCameraCollisionDef" => DefBody::Game(GameBody::CameraCollisionDef(CameraCollisionDef::parse(cur)?)),
        "CAMERA_MANAGER" => DefBody::Game(GameBody::CameraManagerDef(CameraManagerDef::parse(cur)?)),
        "CAMERA_MANAGER_SET" => DefBody::Game(GameBody::CameraManagerSetDef(CameraManagerSetDef::parse(cur)?)),
        "CAMERA_MODE" => DefBody::Game(GameBody::CameraModeDef(CameraModeDef::parse(cur)?)),
        "CCarriedReadableDef" => DefBody::Game(GameBody::CarriedReadableDef(CarriedReadableDef::parse(cur)?)),
        "CARRY_SLOT" => DefBody::Game(GameBody::CarrySlotDef(CarrySlotDef::parse(cur)?)),
        "CCarryableDef" => DefBody::Game(GameBody::CarryableDef(CarryableDef::parse(cur)?)),
        "CCarryingDef" => DefBody::Game(GameBody::CarryingDef(CarryingDef::parse(cur)?)),
        "CChestDef" => DefBody::Game(GameBody::ChestDef(ChestDef::parse(cur)?)),
        "CClockDef" => DefBody::Game(GameBody::ClockDef(ClockDef::parse(cur)?)),
        "CCoinGameObstacleDef" => DefBody::Game(GameBody::CoinGameObstacleDef(CoinGameObstacleDef::parse(cur)?)),
        "CCombatAbilityBlockCounterAttackDef" => DefBody::Game(GameBody::CombatAbilityAttackBase(CombatAbilityAttackBase::parse(cur)?)),
        "CCombatAbilityFlourishCounterAttackDef" => DefBody::Game(GameBody::CombatAbilityAttackBase(CombatAbilityAttackBase::parse(cur)?)),
        "CCombatAbilityGetHitCounterAttackDef" => DefBody::Game(GameBody::CombatAbilityAttackBase(CombatAbilityAttackBase::parse(cur)?)),
        "CCombatAbilityBlockHeavyWeaponAttackDef" => DefBody::Game(GameBody::CombatAbilityBlockDefBase(CombatAbilityBlockDefBase::parse(cur)?)),
        "CCombatAbilityBlockLightWeaponAttackDef" => DefBody::Game(GameBody::CombatAbilityBlockDefBase(CombatAbilityBlockDefBase::parse(cur)?)),
        "CCombatAbilityBlockProjectileWeaponAttackDef" => DefBody::Game(GameBody::CombatAbilityBlockDefBase(CombatAbilityBlockDefBase::parse(cur)?)),
        "CCombatAbilityBlockUnarmedAttackDef" => DefBody::Game(GameBody::CombatAbilityBlockDefBase(CombatAbilityBlockDefBase::parse(cur)?)),
        "CCombatAbilityStrafeDef" => DefBody::Game(GameBody::CombatAbilityStrafeDef(CombatAbilityStrafeDef::parse(cur)?)),
        "CCombatAbilityUseProjectileWeaponDef" => DefBody::Game(GameBody::CombatAbilityUseProjectileWeaponDef(CombatAbilityUseProjectileWeaponDef::parse(cur)?)),
        "COMBAT_DIALOGUE_DEF" => DefBody::Game(GameBody::CombatDialogueDef(CombatDialogueDef::parse(cur)?)),
        "COMBAT_SEQUENCE" => DefBody::Game(GameBody::CombatSequenceDef(CombatSequenceDef::parse(cur)?)),
        "COMBAT_TYPE" => DefBody::Game(GameBody::CombatTypeDef(CombatTypeDef::parse(cur)?)),
        "CContainerRewardHeroDef" => DefBody::Game(GameBody::ContainerRewardHeroDef(ContainerRewardHeroDef::parse(cur)?)),
        "CContextSensitiveItemDef" => DefBody::Game(GameBody::ContextSensitiveItemDef(ContextSensitiveItemDef::parse(cur)?)),
        "CCoopSpiritDef" => DefBody::Game(GameBody::CoopSpiritDef(CoopSpiritDef::parse(cur)?)),
        "CCrateStackDef" => DefBody::Game(GameBody::CrateStackDef(CrateStackDef::parse(cur)?)),
        "CREATURE_ABILITY" => DefBody::Game(GameBody::CreatureAbilityDef(CreatureAbilityDef::parse(cur)?)),
        "CCreatureDef" => DefBody::Game(GameBody::CreatureDef(CreatureDef::parse(cur)?)),
        "CREATURE_GENERATION_FAMILY" => DefBody::Game(GameBody::CreatureGenerationFamilyDef(CreatureGenerationFamilyDef::parse(cur)?)),
        "CCreatureGeneratorDef" => DefBody::Game(GameBody::CreatureGeneratorDef(CreatureGeneratorDef::parse(cur)?)),
        "CCreatureModeDef" => DefBody::Game(GameBody::CreatureModeDef(CreatureModeDef::parse(cur)?)),
        "CCreatureNavigationDef" => DefBody::Game(GameBody::CreatureNavigationDef(CreatureNavigationDef::parse(cur)?)),
        "CCreatureStatsDef" => DefBody::Game(GameBody::CreatureStatsDef(CreatureStatsDef::parse(cur)?)),
        "CCutsceneDef" => DefBody::Game(GameBody::CutsceneDef(CutsceneDef::parse(cur)?)),
        "CDecapitationDef" => DefBody::Game(GameBody::DecapitationDef(DecapitationDef::parse(cur)?)),
        "CDoorDef" => DefBody::Game(GameBody::DoorDef(DoorDef::parse(cur)?)),
        "CDragonActionHoverDef" => DefBody::Game(GameBody::DragonActionHoverDef(DragonActionHoverDef::parse(cur)?)),
        "CDragonActionNapalmDef" => DefBody::Game(GameBody::DragonActionNapalmDef(DragonActionNapalmDef::parse(cur)?)),
        "CDragonActionSwoopDef" => DefBody::Game(GameBody::DragonActionSwoopDef(DragonActionSwoopDef::parse(cur)?)),
        "CDrunkennessDef" => DefBody::Game(GameBody::DrunkennessDef(DrunkennessDef::parse(cur)?)),
        "CEnemyDef" => DefBody::Game(GameBody::EnemyDef(EnemyDef::parse(cur)?)),
        "LOCAL_DETAIL_GENERATOR" => DefBody::Game(GameBody::EngineLocalDetailGeneratorDef(EngineLocalDetailGeneratorDef::parse(cur)?)),
        "ENGINE_THEME" => DefBody::Game(GameBody::EngineThemeDef(EngineThemeDef::parse(cur)?)),
        "ENGINE_THEME_GROUP" => DefBody::Game(GameBody::EngineThemeGroupDef(EngineThemeGroupDef::parse(cur)?)),
        "THING_GROUP" => DefBody::Game(GameBody::EngineThemeGroupDef(EngineThemeGroupDef::parse(cur)?)),
        "CEntitySoundDef" => DefBody::Game(GameBody::EntitySoundDef(EntitySoundDef::parse(cur)?)),
        "CExperienceDef" => DefBody::Game(GameBody::ExperienceDef(ExperienceDef::parse(cur)?)),
        "CExplodingObjectDef" => DefBody::Game(GameBody::ExplodingObjectDef(ExplodingObjectDef::parse(cur)?)),
        "CExplosionDef" => DefBody::Game(GameBody::ExplosionDef(ExplosionDef::parse(cur)?)),
        "CExplosiveTrailDef" => DefBody::Game(GameBody::ExplosiveTrailDef(ExplosiveTrailDef::parse(cur)?)),
        "EXPRESSION" => DefBody::Game(GameBody::ExpressionDef(ExpressionDef::parse(cur)?)),
        "CExpressionSubDef" => DefBody::Game(GameBody::ExpressionSubDef(ExpressionSubDef::parse(cur)?)),
        "FACTION" => DefBody::Game(GameBody::FactionDef(FactionDef::parse(cur)?)),
        "CFireballSpellLevelDef" => DefBody::Game(GameBody::FireballSpellLevelDef(FireballSpellLevelDef::parse(cur)?)),
        "CFireheartMinigameDef" => DefBody::Game(GameBody::FireheartMinigameDef(FireheartMinigameDef::parse(cur)?)),
        "CFishDef" => DefBody::Game(GameBody::FishDef(FishDef::parse(cur)?)),
        "CFishingDef" => DefBody::Game(GameBody::FishingDef(FishingDef::parse(cur)?)),
        "CFishingRodDef" => DefBody::Game(GameBody::FishingRodDef(FishingRodDef::parse(cur)?)),
        "CFlammableDef" => DefBody::Game(GameBody::FlammableDef(FlammableDef::parse(cur)?)),
        "CGiftDef" => DefBody::Game(GameBody::GiftDef(GiftDef::parse(cur)?)),
        "CGoldDef" => DefBody::Game(GameBody::GoldDef(GoldDef::parse(cur)?)),
        "CGuardDef" => DefBody::Game(GameBody::GuardDef(GuardDef::parse(cur)?)),
        "CGuildMasterDef" => DefBody::Game(GameBody::GuildMasterDef(GuildMasterDef::parse(cur)?)),
        "CHairCardDef" => DefBody::Game(GameBody::HairCardDef(HairCardDef::parse(cur)?)),
        "CHasNameDef" => DefBody::Game(GameBody::HasNameDef(HasNameDef::parse(cur)?)),
        "HERO_ABILITY" => DefBody::Game(GameBody::HeroAbilityDef(HeroAbilityDef::parse(cur)?)),
        "CHeroCentreDef" => DefBody::Game(GameBody::HeroCentreDef(HeroCentreDef::parse(cur)?)),
        "HERO_COMBAT" => DefBody::Game(GameBody::HeroCombatDef(HeroCombatDef::parse(cur)?)),
        "CHeroDef" => DefBody::Game(GameBody::HeroDef(HeroDef::parse(cur)?)),
        "CHeroExperienceDef" => DefBody::Game(GameBody::HeroExperienceDef(HeroExperienceDef::parse(cur)?)),
        "CHeroMarriageDef" => DefBody::Game(GameBody::HeroMarriageDef(HeroMarriageDef::parse(cur)?)),
        "CHeroMorphDef" => DefBody::Game(GameBody::HeroMorphDef(HeroMorphDef::parse(cur)?)),
        "CHeroPostcardGeneratorDef" => DefBody::Game(GameBody::HeroPostcardGeneratorDef(HeroPostcardGeneratorDef::parse(cur)?)),
        "CHeroSpecialMovementDef" => DefBody::Game(GameBody::HeroSpecialMovementDef(HeroSpecialMovementDef::parse(cur)?)),
        "HERO_STATS" => DefBody::Game(GameBody::HeroStatsDef(HeroStatsDef::parse(cur)?)),
        "CHeroSuitDef" => DefBody::Game(GameBody::HeroSuitDef(HeroSuitDef::parse(cur)?)),
        "CHeroTitleDef" => DefBody::Game(GameBody::HeroTitleDef(HeroTitleDef::parse(cur)?)),
        "CHighlightItemDef" => DefBody::Game(GameBody::HighlightItemDef(HighlightItemDef::parse(cur)?)),
        "HIT_LOCATION" => DefBody::Game(GameBody::HitLocationDef(HitLocationDef::parse(cur)?)),
        "CHitLocationsDef" => DefBody::Game(GameBody::HitLocationsDef(HitLocationsDef::parse(cur)?)),
        "CIdleSchedulerDef" => DefBody::Game(GameBody::IdleSchedulerDef(IdleSchedulerDef::parse(cur)?)),
        "CInterestingToVillagersDef" => DefBody::Game(GameBody::InterestingToVillagersDef(InterestingToVillagersDef::parse(cur)?)),
        "INVENTORY_CATEGORY" => DefBody::Game(GameBody::InventoryCategoryDef(InventoryCategoryDef::parse(cur)?)),
        "INVENTORY_TYPE" => DefBody::Game(GameBody::InventoryDef(InventoryDef::parse(cur)?)),
        "CInventoryItemDef" => DefBody::Game(GameBody::InventoryItemDef(InventoryItemDef::parse(cur)?)),
        "INVENTORY_ITEM" => DefBody::Game(GameBody::InventoryItemDef(InventoryItemDef::parse(cur)?)),
        "CJackDragonDef" => DefBody::Game(GameBody::JackDragonDef(JackDragonDef::parse(cur)?)),
        "CJackOfBladesBattleDef" => DefBody::Game(GameBody::JackOfBladesBattleDef(JackOfBladesBattleDef::parse(cur)?)),
        "CKickableDef" => DefBody::Game(GameBody::KickableDef(KickableDef::parse(cur)?)),
        "CKrakenDef" => DefBody::Game(GameBody::KrakenDef(KrakenDef::parse(cur)?)),
        "CKrakenTentacleDef" => DefBody::Game(GameBody::KrakenTentacleDef(KrakenTentacleDef::parse(cur)?)),
        "CLightDef" => DefBody::Game(GameBody::LightDef(LightDef::parse(cur)?)),
        "LIGHTNING" => DefBody::Game(GameBody::LightningDef(LightningDef::parse(cur)?)),
        "CLightningOrbDef" => DefBody::Game(GameBody::LightningOrbDef(LightningOrbDef::parse(cur)?)),
        "CLookDef" => DefBody::Game(GameBody::LookDef(LookDef::parse(cur)?)),
        "MATERIAL" => DefBody::Game(GameBody::MaterialDef(MaterialDef::parse(cur)?)),
        "CMazeBattleDef" => DefBody::Game(GameBody::MazeBattleDef(MazeBattleDef::parse(cur)?)),
        "HERO_MELEE_COMBAT_ABILITY" => DefBody::Game(GameBody::MeleeCombatAbilityDef(MeleeCombatAbilityDef::parse(cur)?)),
        "MELEE_COMBAT_KNOCKDOWN_EFFECTS" => DefBody::Game(GameBody::MeleeCombatKnockdownEffects(MeleeCombatKnockdownEffects::parse(cur)?)),
        "MESSAGE_EVENT" => DefBody::Game(GameBody::MessageEventDef(MessageEventDef::parse(cur)?)),
        "CMultiStaticMeshDef" => DefBody::Game(GameBody::MultiStaticMeshDef(MultiStaticMeshDef::parse(cur)?)),
        "CNymphDef" => DefBody::Game(GameBody::NymphDef(NymphDef::parse(cur)?)),
        "CObjectAugmentationsDef" => DefBody::Game(GameBody::ObjectAugmentationsDef(ObjectAugmentationsDef::parse(cur)?)),
        "OBJECT_FAMILY" => DefBody::Game(GameBody::ObjectFamilyDef(ObjectFamilyDef::parse(cur)?)),
        "COccupiableDef" => DefBody::Game(GameBody::OccupiableDef(OccupiableDef::parse(cur)?)),
        "OPINION_DEED_EFFECTS" => DefBody::Game(GameBody::OpinionDeedEffectsDef(OpinionDeedEffectsDef::parse(cur)?)),
        "OPINION_DEED_MASK" => DefBody::Game(GameBody::OpinionDeedMaskDef(OpinionDeedMaskDef::parse(cur)?)),
        "COpinionOfHeroDef" => DefBody::Game(GameBody::OpinionOfHeroDef(OpinionOfHeroDef::parse(cur)?)),
        "OPINION_PERSONALITY" => DefBody::Game(GameBody::OpinionPersonalityDef(OpinionPersonalityDef::parse(cur)?)),
        "OPINION_REACTION_MANAGER" => DefBody::Game(GameBody::OpinionReactionManagerDef(OpinionReactionManagerDef::parse(cur)?)),
        "OPINION_REACTION_MASK" => DefBody::Game(GameBody::OpinionReactionMaskDef(OpinionReactionMaskDef::parse(cur)?)),
        "OPINION_SOURCE" => DefBody::Game(GameBody::OpinionSourceDef(OpinionSourceDef::parse(cur)?)),
        "COracleMinigameDef" => DefBody::Game(GameBody::OracleMinigameDef(OracleMinigameDef::parse(cur)?)),
        "COverheadDisplayDef" => DefBody::Game(GameBody::OverheadDisplayDef(OverheadDisplayDef::parse(cur)?)),
        "CParticleAttacherDef" => DefBody::Game(GameBody::ParticleAttacherDef(ParticleAttacherDef::parse(cur)?)),
        "CPerceivedThingDef" => DefBody::Game(GameBody::PerceivedThingDef(PerceivedThingDef::parse(cur)?)),
        "CPhysicsDef" => DefBody::Game(GameBody::PhysicsDef(PhysicsDef::parse(cur)?)),
        "PLAYER" => DefBody::Game(GameBody::PlayerDef(PlayerDef::parse(cur)?)),
        "PLAYER_GUI" => DefBody::Game(GameBody::PlayerGuiDef(PlayerGuiDef::parse(cur)?)),
        "PLAYER_INVENTORY" => DefBody::Game(GameBody::PlayerInventoryDef(PlayerInventoryDef::parse(cur)?)),
        "CQuestCardDef" => DefBody::Game(GameBody::QuestCardDef(QuestCardDef::parse(cur)?)),
        "CReadableDef" => DefBody::Game(GameBody::ReadableDef(ReadableDef::parse(cur)?)),
        "REGION" => DefBody::Game(GameBody::RegionDef(RegionDef::parse(cur)?)),
        "CRegionScriptDef" => DefBody::Game(GameBody::RegionScriptDef(RegionScriptDef::parse(cur)?)),
        "CResurrectionItemDef" => DefBody::Game(GameBody::ResurrectionItemDef(ResurrectionItemDef::parse(cur)?)),
        "CRumbleDef" => DefBody::Game(GameBody::RumbleDef(RumbleDef::parse(cur)?)),
        "CScorpionKingBattleDef" => DefBody::Game(GameBody::ScorpionKingBattleDef(ScorpionKingBattleDef::parse(cur)?)),
        "CScriptDef" => DefBody::Game(GameBody::ScriptDef(ScriptDef::parse(cur)?)),
        "CShipDef" => DefBody::Game(GameBody::ShipDef(ShipDef::parse(cur)?)),
        "SIM_BUILDING" => DefBody::Game(GameBody::SimBuildingDef(SimBuildingDef::parse(cur)?)),
        "SIM_VOICES" => DefBody::Game(GameBody::SimVoicesDef(SimVoicesDef::parse(cur)?)),
        "CSkeletalMorphDef" => DefBody::Game(GameBody::SkeletalMorphDef(SkeletalMorphDef::parse(cur)?)),
        "SKY" => DefBody::Game(GameBody::SkyDef(SkyDef::parse(cur)?)),
        "CSmashableDef" => DefBody::Game(GameBody::SmashableDef(SmashableDef::parse(cur)?)),
        "CSmokeGeneratorDef" => DefBody::Game(GameBody::SmokeGeneratorDef(SmokeGeneratorDef::parse(cur)?)),
        "CSnowTrollDef" => DefBody::Game(GameBody::SnowTrollDef(SnowTrollDef::parse(cur)?)),
        "CSoundAtmospheresDef" => DefBody::Game(GameBody::SoundAtmospheresDef(SoundAtmospheresDef::parse(cur)?)),
        "SOUND_SETUP" => DefBody::Game(GameBody::SoundDef(SoundDef::parse(cur)?)),
        "SOUND_THEME" => DefBody::Game(GameBody::SoundThemeDef(SoundThemeDef::parse(cur)?)),
        "SPECIAL_ABILITIES_ASSASSIN_RUSH_DEF" => DefBody::Game(GameBody::SpecialAbilitiesAssassinRushDef(SpecialAbilitiesAssassinRushDef::parse(cur)?)),
        "SPECIAL_ABILITIES_BATTLE_CHARGE_DEF" => DefBody::Game(GameBody::SpecialAbilitiesBattleChargeDef(SpecialAbilitiesBattleChargeDef::parse(cur)?)),
        "SPECIAL_ABILITIES_BERSERK_DEF" => DefBody::Game(GameBody::SpecialAbilitiesBerserkDef(SpecialAbilitiesBerserkDef::parse(cur)?)),
        "SPECIAL_ABILITIES_BULLET_TIME_DEF" => DefBody::Game(GameBody::SpecialAbilitiesBulletTimeDef(SpecialAbilitiesBulletTimeDef::parse(cur)?)),
        "SPECIAL_ABILITIES_BURNT_EFFECT_DEF" => DefBody::Game(GameBody::SpecialAbilitiesBurntEffectDef(SpecialAbilitiesBurntEffectDef::parse(cur)?)),
        "SPECIAL_ABILITIES_CREATURE_TINT_DEF" => DefBody::Game(GameBody::SpecialAbilitiesCreatureTintDef(SpecialAbilitiesCreatureTintDef::parse(cur)?)),
        "SPECIAL_ABILITIES_DRAIN_LIFE_DEF" => DefBody::Game(GameBody::SpecialAbilitiesDrainLifeDef(SpecialAbilitiesDrainLifeDef::parse(cur)?)),
        "SPECIAL_ABILITIES_DRUNKENNESS_DEF" => DefBody::Game(GameBody::SpecialAbilitiesDrunkennessDef(SpecialAbilitiesDrunkennessDef::parse(cur)?)),
        "SPECIAL_ABILITIES_ELECTROCUTED_EFFECT_DEF" => DefBody::Game(GameBody::SpecialAbilitiesElectrocutedEffectDef(SpecialAbilitiesElectrocutedEffectDef::parse(cur)?)),
        "SPECIAL_ABILITIES_ENFLAME_DEF" => DefBody::Game(GameBody::SpecialAbilitiesEnflameDef(SpecialAbilitiesEnflameDef::parse(cur)?)),
        "SPECIAL_ABILITIES_FIREBALL_SPELL_DEF" => DefBody::Game(GameBody::SpecialAbilitiesFireballSpellDef(SpecialAbilitiesFireballSpellDef::parse(cur)?)),
        "CSpecialAbilitiesDrainLifeDataDef" => DefBody::Game(GameBody::SpecialAbilitiesForcePushDataDef(SpecialAbilitiesForcePushDataDef::parse(cur)?)),
        "CSpecialAbilitiesForcePushDataDef" => DefBody::Game(GameBody::SpecialAbilitiesForcePushDataDef(SpecialAbilitiesForcePushDataDef::parse(cur)?)),
        "SPECIAL_ABILITIES_FORCE_PUSH_DEF" => DefBody::Game(GameBody::SpecialAbilitiesForcePushDef(SpecialAbilitiesForcePushDef::parse(cur)?)),
        "SPECIAL_ABILITIES_GHOST_SWORD_DEF" => DefBody::Game(GameBody::SpecialAbilitiesGhostSwordDef(SpecialAbilitiesGhostSwordDef::parse(cur)?)),
        "SPECIAL_ABILITIES_HEAL_LIFE_DEF" => DefBody::Game(GameBody::SpecialAbilitiesHealLifeDef(SpecialAbilitiesHealLifeDef::parse(cur)?)),
        "SPECIAL_ABILITIES_LIGHTNING_SPELL_DEF" => DefBody::Game(GameBody::SpecialAbilitiesLightningSpellDef(SpecialAbilitiesLightningSpellDef::parse(cur)?)),
        "SPECIAL_ABILITIES_MULTI_ARROW_DEF" => DefBody::Game(GameBody::SpecialAbilitiesMultiArrowDef(SpecialAbilitiesMultiArrowDef::parse(cur)?)),
        "SPECIAL_ABILITIES_MULTI_STRIKE_DEF" => DefBody::Game(GameBody::SpecialAbilitiesMultiStrikeDef(SpecialAbilitiesMultiStrikeDef::parse(cur)?)),
        "SPECIAL_ABILITIES_PHYSICAL_SHIELD_DEF" => DefBody::Game(GameBody::SpecialAbilitiesPhysicalShieldDef(SpecialAbilitiesPhysicalShieldDef::parse(cur)?)),
        "SPECIAL_ABILITIES_SUMMON_SPELL_DEF" => DefBody::Game(GameBody::SpecialAbilitiesSummonSpellDef(SpecialAbilitiesSummonSpellDef::parse(cur)?)),
        "SPECIAL_ABILITIES_THUNDER_LIGHTNING_STORM_DEF" => DefBody::Game(GameBody::SpecialAbilitiesThunderLightningStormDef(SpecialAbilitiesThunderLightningStormDef::parse(cur)?)),
        "SPECIAL_ABILITIES_TURNCOAT_SPELL_DEF" => DefBody::Game(GameBody::SpecialAbilitiesTurncoatSpellDef(SpecialAbilitiesTurncoatSpellDef::parse(cur)?)),
        "SPECIAL_ABILITIES_DIVINE_WRATH_DEF" => DefBody::Game(GameBody::SpecialAbilitiesUnholyPowerDef(SpecialAbilitiesUnholyPowerDef::parse(cur)?)),
        "SPECIAL_ABILITIES_UNHOLY_POWER_DEF" => DefBody::Game(GameBody::SpecialAbilitiesUnholyPowerDef(SpecialAbilitiesUnholyPowerDef::parse(cur)?)),
        "CSpecialEffectsDef" => DefBody::Game(GameBody::SpecialEffectsDef(SpecialEffectsDef::parse(cur)?)),
        "CSpotLightDef" => DefBody::Game(GameBody::SpotLightDef(SpotLightDef::parse(cur)?)),
        "CStealthDef" => DefBody::Game(GameBody::StealthDef(StealthDef::parse(cur)?)),
        "CStockItemDef" => DefBody::Game(GameBody::StockItemDef(StockItemDef::parse(cur)?)),
        "CSummonDef" => DefBody::Game(GameBody::SummonDef(SummonDef::parse(cur)?)),
        "CSummonableCreatureDef" => DefBody::Game(GameBody::SummonableCreatureDef(SummonableCreatureDef::parse(cur)?)),
        "CSummonerDef" => DefBody::Game(GameBody::SummonerDef(SummonerDef::parse(cur)?)),
        "CTCVolumeContainmentTrackerDef" => DefBody::Game(GameBody::TCVolumeContainmentTrackerDef(TCVolumeContainmentTrackerDef::parse(cur)?)),
        "CTargetingDef" => DefBody::Game(GameBody::TargetingDef(TargetingDef::parse(cur)?)),
        "CTattooDef" => DefBody::Game(GameBody::TattooDef(TattooDef::parse(cur)?)),
        "CTavernDef" => DefBody::Game(GameBody::TavernDef(TavernDef::parse(cur)?)),
        "CTavernGameCardBaseDef" => DefBody::Game(GameBody::TavernGameCardBaseDef(TavernGameCardBaseDef::parse(cur)?)),
        "CTavernGameCoinBaseDef" => DefBody::Game(GameBody::TavernGameCoinBaseDef(TavernGameCoinBaseDef::parse(cur)?)),
        "CTavernGameCoinGolfDef" => DefBody::Game(GameBody::TavernGameCoinGolfDef(TavernGameCoinGolfDef::parse(cur)?)),
        "CTavernGameDef" => DefBody::Game(GameBody::TavernGameDef(TavernGameDef::parse(cur)?)),
        "CTavernGameShoveHaPennyDef" => DefBody::Game(GameBody::TavernGameShoveHaPennyDef(TavernGameShoveHaPennyDef::parse(cur)?)),
        "CTavernGameSpotTheAdditionDef" => DefBody::Game(GameBody::TavernGameSpotTheAdditionDef(TavernGameSpotTheAdditionDef::parse(cur)?)),
        "CTavernTableDef" => DefBody::Game(GameBody::TavernTableDef(TavernTableDef::parse(cur)?)),
        "CTeleporterDef" => DefBody::Game(GameBody::TeleporterDef(TeleporterDef::parse(cur)?)),
        "CTextureReplacementDef" => DefBody::Game(GameBody::TextureReplacementDef(TextureReplacementDef::parse(cur)?)),
        "THING" => DefBody::Game(GameBody::ThingBaseDef(ThingBaseDef::parse(cur)?)),
        "BUILDING" => DefBody::Game(GameBody::ThingBuildingDef(ThingBuildingDef::parse(cur)?)),
        "CREATURE" => DefBody::Game(GameBody::ThingCreatureDef(ThingCreatureDef::parse(cur)?)),
        "CThingDrainLifeShotDef" => DefBody::Game(GameBody::ThingDrainLifeShotDef(ThingDrainLifeShotDef::parse(cur)?)),
        "HOLY_SITE" => DefBody::Game(GameBody::ThingHolySiteDef(ThingHolySiteDef::parse(cur)?)),
        "MARKER" => DefBody::Game(GameBody::ThingMarkerDef(ThingMarkerDef::parse(cur)?)),
        "CThingMultiArrowShotDef" => DefBody::Game(GameBody::ThingMultiArrowShotDef(ThingMultiArrowShotDef::parse(cur)?)),
        "NOISE" => DefBody::Game(GameBody::ThingNoiseDef(ThingNoiseDef::parse(cur)?)),
        "OBJECT" => DefBody::Game(GameBody::ThingObjectDef(ThingObjectDef::parse(cur)?)),
        "PHYSICAL_SWITCH" => DefBody::Game(GameBody::ThingPhysicalSwitchDef(ThingPhysicalSwitchDef::parse(cur)?)),
        "SHOT" => DefBody::Game(GameBody::ThingShotDef(ThingShotDef::parse(cur)?)),
        "SWITCH" => DefBody::Game(GameBody::ThingSwitchDef(ThingSwitchDef::parse(cur)?)),
        "VILLAGE" => DefBody::Game(GameBody::ThingVillageDef(ThingVillageDef::parse(cur)?)),
        "CThunderBattleDef" => DefBody::Game(GameBody::ThunderBattleDef(ThunderBattleDef::parse(cur)?)),
        "CTimeAppearanceFadeDef" => DefBody::Game(GameBody::TimeAppearanceFadeDef(TimeAppearanceFadeDef::parse(cur)?)),
        "CTrapDef" => DefBody::Game(GameBody::TrapDef(TrapDef::parse(cur)?)),
        "CTrollBattleDef" => DefBody::Game(GameBody::TrollBattleDef(TrollBattleDef::parse(cur)?)),
        "CTrophyDef" => DefBody::Game(GameBody::TrophyDef(TrophyDef::parse(cur)?)),
        "CTurncoatDef" => DefBody::Game(GameBody::TurncoatDef(TurncoatDef::parse(cur)?)),
        "UI_LOCALE_GRAPHICS_DEF" => DefBody::Game(GameBody::UILocaleGraphicsDef(UILocaleGraphicsDef::parse(cur)?)),
        "UI_MISC_THINGS_DEF" => DefBody::Game(GameBody::UiMiscThingsDef(UiMiscThingsDef::parse(cur)?)),
        "CVillageDef" => DefBody::Game(GameBody::VillageDef(VillageDef::parse(cur)?)),
        "CVillageMemberDef" => DefBody::Game(GameBody::VillageMemberDef(VillageMemberDef::parse(cur)?)),
        "CVillagePeopleDef" => DefBody::Game(GameBody::VillagePeopleDef(VillagePeopleDef::parse(cur)?)),
        "VILLAGER_INTERACTION" => DefBody::Game(GameBody::VillagerInteractionsDef(VillagerInteractionsDef::parse(cur)?)),
        "CWallMountEffectsDef" => DefBody::Game(GameBody::WallMountEffectsDef(WallMountEffectsDef::parse(cur)?)),
        "CWaspQueenBattleDef" => DefBody::Game(GameBody::WaspQueenBattleDef(WaspQueenBattleDef::parse(cur)?)),
        "CWeaponDef" => DefBody::Game(GameBody::WeaponDef(WeaponDef::parse(cur)?)),
        "CWhisperBattleDef" => DefBody::Game(GameBody::WhisperBattleDef(WhisperBattleDef::parse(cur)?)),
        "CWifeDef" => DefBody::Game(GameBody::WifeDef(WifeDef::parse(cur)?)),
        "CWillResponseDef" => DefBody::Game(GameBody::WillResponseDef(WillResponseDef::parse(cur)?)),
        "CDegradableDef" => DefBody::Game(GameBody::DegradableDef(DegradableDef::parse(cur)?)),
        "CReplaceableMeshDef" => DefBody::Game(GameBody::ReplaceableMeshDef(ReplaceableMeshDef::parse(cur)?)),
        "GLOBAL" => DefBody::Game(GameBody::GlobalDef(GlobalDef::parse(cur)?)),
        "PLAYER_MOVEMENT" => DefBody::Game(GameBody::PlayerMovementDef(PlayerMovementDef::parse(cur)?)),
        "CAppearanceModifierDef" => DefBody::Game(GameBody::AppearanceModifierDef(AppearanceModifierDef::parse(cur)?)),
        "CShopDef" => DefBody::Game(GameBody::ShopDef(ShopDef::parse(cur)?)),
        "CShopItemDef" => DefBody::Game(GameBody::ShopItemDef(ShopItemDef::parse(cur)?)),
        _ => return Ok(None),
    }))
}

pub fn parse_script_def(
    name: &str,
    cur: &mut &[u8],
) -> Result<DefBody, ParseControlError> {
    Ok(match parse_game_def(name, cur)? {
        Some(body) => body,
        None => DefBody::Unknown {
            name: name.to_string(),
            bytes: core::mem::take(cur).to_vec(),
        },
    })
}

/// Copy fields that lowering deliberately *preserves* (rather than computes)
/// from a reference entry's body. Currently that's the Thing component list:
/// its per-entry records are opaque to the lowerer (`Components.Add` edits
/// are future from-scratch-compiler work), so the reference's value is kept.
pub fn preserve_unlowered(lowered: &mut DefBody, reference: &DefBody) {
    use crate::def::binary::def_binary::DefBody as D;
    match (lowered, reference) {
        (D::Game(GameBody::ThingBaseDef(a)), D::Game(GameBody::ThingBaseDef(b))) => {
            a.components = b.components.clone();
        }
        (D::Game(GameBody::ThingBuildingDef(a)), D::Game(GameBody::ThingBuildingDef(b))) => {
            a.components = b.components.clone();
        }
        (D::Game(GameBody::ThingCreatureDef(a)), D::Game(GameBody::ThingCreatureDef(b))) => {
            a.components = b.components.clone();
        }
        (D::Game(GameBody::ThingHolySiteDef(a)), D::Game(GameBody::ThingHolySiteDef(b))) => {
            a.components = b.components.clone();
        }
        (D::Game(GameBody::ThingMarkerDef(a)), D::Game(GameBody::ThingMarkerDef(b))) => {
            a.components = b.components.clone();
        }
        (D::Game(GameBody::ThingNoiseDef(a)), D::Game(GameBody::ThingNoiseDef(b))) => {
            a.components = b.components.clone();
        }
        (D::Game(GameBody::ThingObjectDef(a)), D::Game(GameBody::ThingObjectDef(b))) => {
            a.components = b.components.clone();
        }
        (D::Game(GameBody::ThingPhysicalSwitchDef(a)), D::Game(GameBody::ThingPhysicalSwitchDef(b))) => {
            a.components = b.components.clone();
        }
        (D::Game(GameBody::ThingSwitchDef(a)), D::Game(GameBody::ThingSwitchDef(b))) => {
            a.components = b.components.clone();
        }
        (D::Game(GameBody::ThingVillageDef(a)), D::Game(GameBody::ThingVillageDef(b))) => {
            a.components = b.components.clone();
        }
        _ => {}
    }
}
