//! Canonical game-def table — the single source of truth for the
//! `(wire name(s), GameBody variant, def struct)` mapping.
//!
//! Every game def is listed here exactly once as `Variant => ["WireName", …]`
//! (the def struct type is always identical to the variant name). This macro is
//! consumed by callback macros to generate what were previously six parallel
//! hand-maintained ~240-arm matches:
//!   - `def/dispatch.rs`     — the `GameBody` enum + `serialize` / `byte_size` /
//!                             `visit_active` / `parse_game_def`
//!   - `fable-def-compiler`  — `lower_generic::plain_lower` (the generic lowering
//!                             fallthrough)
//!
//! To add a def: add its struct module, then add ONE line here. Bespoke lowering
//! (defs needing more than the generic field walk) is layered on top in
//! `lower_game_def` and does not belong in this table.
//!
//! A callback receives the list as:
//! ```ignore
//! macro_rules! my_cb {
//!     ($($variant:ident => [$($name:literal),+ $(,)?]),+ $(,)?) => { /* … */ };
//! }
//! for_each_game_def!(my_cb);
//! ```

/// Invoke `$cb!` with the full game-def table (see module docs).
#[macro_export]
macro_rules! for_each_game_def {
    ($cb:ident) => {
        $cb! {
        AbilityDef => ["CAbilityDef"],
        ActionUseDef => ["CActionUseDef"],
        ActivateQuestDef => ["CActivateQuestDef"],
        AICreatureWillPowerIndicatorDef => ["CAICreatureWillPowerIndicatorDef"],
        AIScratchpadDef => ["CAIScratchpadDef"],
        AnimatingObjectDef => ["CAnimatingObjectDef"],
        AppearanceDef => ["CAppearanceDef"],
        AreaOfEffectAttackDef => ["CAreaOfEffectAttackDef"],
        ArmourDef => ["ARMOUR"],
        AttackPatternDef => ["ATTACK_PATTERN"],
        AugmentationDef => ["CAugmentationDef"],
        BalverineBattleDef => ["CBalverineBattleDef"],
        BedDef => ["CBedDef"],
        BettingDef => ["CBettingDef"],
        BoastingPodiumDef => ["CBoastingPodiumDef"],
        BonusItemDef => ["CBonusItemDef"],
        BossDef => ["CBossDef"],
        BrainDef => ["BRAIN"],
        BriarRoseDef => ["CBriarRoseDef"],
        BuyHouseDef => ["CBuyHouseDef"],
        BuyableHouseDef => ["CBuyableHouseDef"],
        CameraCollisionDef => ["CCameraCollisionDef"],
        CameraManagerDef => ["CAMERA_MANAGER"],
        CameraManagerSetDef => ["CAMERA_MANAGER_SET"],
        CameraModeDef => ["CAMERA_MODE"],
        CarriedReadableDef => ["CCarriedReadableDef"],
        CarrySlotDef => ["CARRY_SLOT"],
        CarryableDef => ["CCarryableDef"],
        CarryingDef => ["CCarryingDef"],
        ChestDef => ["CChestDef"],
        ClockDef => ["CClockDef"],
        CoinGameObstacleDef => ["CCoinGameObstacleDef"],
        CombatAbilityAttackBase => ["CCombatAbilityBlockCounterAttackDef", "CCombatAbilityFlourishCounterAttackDef", "CCombatAbilityGetHitCounterAttackDef"],
        CombatAbilityBlockDefBase => ["CCombatAbilityBlockHeavyWeaponAttackDef", "CCombatAbilityBlockLightWeaponAttackDef", "CCombatAbilityBlockProjectileWeaponAttackDef", "CCombatAbilityBlockUnarmedAttackDef"],
        CombatAbilityStrafeDef => ["CCombatAbilityStrafeDef"],
        CombatAbilityUseProjectileWeaponDef => ["CCombatAbilityUseProjectileWeaponDef"],
        CombatDialogueDef => ["COMBAT_DIALOGUE_DEF"],
        CombatSequenceDef => ["COMBAT_SEQUENCE"],
        CombatTypeDef => ["COMBAT_TYPE"],
        ContainerRewardHeroDef => ["CContainerRewardHeroDef"],
        ContextSensitiveItemDef => ["CContextSensitiveItemDef"],
        CoopSpiritDef => ["CCoopSpiritDef"],
        CrateStackDef => ["CCrateStackDef"],
        CreatureAbilityDef => ["CREATURE_ABILITY"],
        CreatureDef => ["CCreatureDef"],
        CreatureGenerationFamilyDef => ["CREATURE_GENERATION_FAMILY"],
        CreatureGeneratorDef => ["CCreatureGeneratorDef"],
        CreatureModeDef => ["CCreatureModeDef"],
        CreatureNavigationDef => ["CCreatureNavigationDef"],
        CreatureStatsDef => ["CCreatureStatsDef"],
        CutsceneDef => ["CCutsceneDef"],
        DecapitationDef => ["CDecapitationDef"],
        DoorDef => ["CDoorDef"],
        DragonActionHoverDef => ["CDragonActionHoverDef"],
        DragonActionNapalmDef => ["CDragonActionNapalmDef"],
        DragonActionSwoopDef => ["CDragonActionSwoopDef"],
        DrunkennessDef => ["CDrunkennessDef"],
        EnemyDef => ["CEnemyDef"],
        EngineLocalDetailGeneratorDef => ["LOCAL_DETAIL_GENERATOR"],
        EngineThemeDef => ["ENGINE_THEME"],
        EngineThemeGroupDef => ["ENGINE_THEME_GROUP", "THING_GROUP"],
        EntitySoundDef => ["CEntitySoundDef"],
        ExperienceDef => ["CExperienceDef"],
        ExplodingObjectDef => ["CExplodingObjectDef"],
        ExplosionDef => ["CExplosionDef"],
        ExplosiveTrailDef => ["CExplosiveTrailDef"],
        ExpressionDef => ["EXPRESSION"],
        ExpressionSubDef => ["CExpressionSubDef"],
        FactionDef => ["FACTION"],
        FireballSpellLevelDef => ["CFireballSpellLevelDef"],
        FireheartMinigameDef => ["CFireheartMinigameDef"],
        FishDef => ["CFishDef"],
        FishingDef => ["CFishingDef"],
        FishingRodDef => ["CFishingRodDef"],
        FlammableDef => ["CFlammableDef"],
        GiftDef => ["CGiftDef"],
        GoldDef => ["CGoldDef"],
        GuardDef => ["CGuardDef"],
        GuildMasterDef => ["CGuildMasterDef"],
        HairCardDef => ["CHairCardDef"],
        HasNameDef => ["CHasNameDef"],
        HeroAbilityDef => ["HERO_ABILITY"],
        HeroCentreDef => ["CHeroCentreDef"],
        HeroCombatDef => ["HERO_COMBAT"],
        HeroDef => ["CHeroDef"],
        HeroExperienceDef => ["CHeroExperienceDef"],
        HeroMarriageDef => ["CHeroMarriageDef"],
        HeroMorphDef => ["CHeroMorphDef"],
        HeroPostcardGeneratorDef => ["CHeroPostcardGeneratorDef"],
        HeroSpecialMovementDef => ["CHeroSpecialMovementDef"],
        HeroStatsDef => ["HERO_STATS"],
        HeroSuitDef => ["CHeroSuitDef"],
        HeroTitleDef => ["CHeroTitleDef"],
        HighlightItemDef => ["CHighlightItemDef"],
        HitLocationDef => ["HIT_LOCATION"],
        HitLocationsDef => ["CHitLocationsDef"],
        IdleSchedulerDef => ["CIdleSchedulerDef"],
        InterestingToVillagersDef => ["CInterestingToVillagersDef"],
        InventoryCategoryDef => ["INVENTORY_CATEGORY"],
        InventoryDef => ["INVENTORY_TYPE"],
        InventoryItemDef => ["CInventoryItemDef", "INVENTORY_ITEM"],
        JackDragonDef => ["CJackDragonDef"],
        JackOfBladesBattleDef => ["CJackOfBladesBattleDef"],
        KickableDef => ["CKickableDef"],
        KrakenDef => ["CKrakenDef"],
        KrakenTentacleDef => ["CKrakenTentacleDef"],
        LightDef => ["CLightDef"],
        LightningDef => ["LIGHTNING"],
        LightningOrbDef => ["CLightningOrbDef"],
        LookDef => ["CLookDef"],
        MaterialDef => ["MATERIAL"],
        MazeBattleDef => ["CMazeBattleDef"],
        MeleeCombatAbilityDef => ["HERO_MELEE_COMBAT_ABILITY"],
        MeleeCombatKnockdownEffects => ["MELEE_COMBAT_KNOCKDOWN_EFFECTS"],
        MessageEventDef => ["MESSAGE_EVENT"],
        MultiStaticMeshDef => ["CMultiStaticMeshDef"],
        NymphDef => ["CNymphDef"],
        ObjectAugmentationsDef => ["CObjectAugmentationsDef"],
        ObjectFamilyDef => ["OBJECT_FAMILY"],
        OccupiableDef => ["COccupiableDef"],
        OpinionDeedEffectsDef => ["OPINION_DEED_EFFECTS"],
        OpinionDeedMaskDef => ["OPINION_DEED_MASK"],
        OpinionOfHeroDef => ["COpinionOfHeroDef"],
        OpinionPersonalityDef => ["OPINION_PERSONALITY"],
        OpinionReactionManagerDef => ["OPINION_REACTION_MANAGER"],
        OpinionReactionMaskDef => ["OPINION_REACTION_MASK"],
        OpinionSourceDef => ["OPINION_SOURCE"],
        OracleMinigameDef => ["COracleMinigameDef"],
        OverheadDisplayDef => ["COverheadDisplayDef"],
        ParticleAttacherDef => ["CParticleAttacherDef"],
        PerceivedThingDef => ["CPerceivedThingDef"],
        PhysicsDef => ["CPhysicsDef"],
        PlayerDef => ["PLAYER"],
        PlayerGuiDef => ["PLAYER_GUI"],
        PlayerInventoryDef => ["PLAYER_INVENTORY"],
        QuestCardDef => ["CQuestCardDef"],
        ReadableDef => ["CReadableDef"],
        RegionDef => ["REGION"],
        RegionScriptDef => ["CRegionScriptDef"],
        ResurrectionItemDef => ["CResurrectionItemDef"],
        RumbleDef => ["CRumbleDef"],
        ScorpionKingBattleDef => ["CScorpionKingBattleDef"],
        ScriptDef => ["CScriptDef"],
        ShipDef => ["CShipDef"],
        SimBuildingDef => ["SIM_BUILDING"],
        SimVoicesDef => ["SIM_VOICES"],
        SkeletalMorphDef => ["CSkeletalMorphDef"],
        SkyDef => ["SKY"],
        SmashableDef => ["CSmashableDef"],
        SmokeGeneratorDef => ["CSmokeGeneratorDef"],
        SnowTrollDef => ["CSnowTrollDef"],
        SoundAtmospheresDef => ["CSoundAtmospheresDef"],
        SoundDef => ["SOUND_SETUP"],
        SoundThemeDef => ["SOUND_THEME"],
        SpecialAbilitiesAssassinRushDef => ["SPECIAL_ABILITIES_ASSASSIN_RUSH_DEF"],
        SpecialAbilitiesBattleChargeDef => ["SPECIAL_ABILITIES_BATTLE_CHARGE_DEF"],
        SpecialAbilitiesBerserkDef => ["SPECIAL_ABILITIES_BERSERK_DEF"],
        SpecialAbilitiesBulletTimeDef => ["SPECIAL_ABILITIES_BULLET_TIME_DEF"],
        SpecialAbilitiesBurntEffectDef => ["SPECIAL_ABILITIES_BURNT_EFFECT_DEF"],
        SpecialAbilitiesCreatureTintDef => ["SPECIAL_ABILITIES_CREATURE_TINT_DEF"],
        SpecialAbilitiesDrainLifeDef => ["SPECIAL_ABILITIES_DRAIN_LIFE_DEF"],
        SpecialAbilitiesDrunkennessDef => ["SPECIAL_ABILITIES_DRUNKENNESS_DEF"],
        SpecialAbilitiesElectrocutedEffectDef => ["SPECIAL_ABILITIES_ELECTROCUTED_EFFECT_DEF"],
        SpecialAbilitiesEnflameDef => ["SPECIAL_ABILITIES_ENFLAME_DEF"],
        SpecialAbilitiesFireballSpellDef => ["SPECIAL_ABILITIES_FIREBALL_SPELL_DEF"],
        SpecialAbilitiesForcePushDataDef => ["CSpecialAbilitiesDrainLifeDataDef", "CSpecialAbilitiesForcePushDataDef"],
        SpecialAbilitiesForcePushDef => ["SPECIAL_ABILITIES_FORCE_PUSH_DEF"],
        SpecialAbilitiesGhostSwordDef => ["SPECIAL_ABILITIES_GHOST_SWORD_DEF"],
        SpecialAbilitiesHealLifeDef => ["SPECIAL_ABILITIES_HEAL_LIFE_DEF"],
        SpecialAbilitiesLightningSpellDef => ["SPECIAL_ABILITIES_LIGHTNING_SPELL_DEF"],
        SpecialAbilitiesMultiArrowDef => ["SPECIAL_ABILITIES_MULTI_ARROW_DEF"],
        SpecialAbilitiesMultiStrikeDef => ["SPECIAL_ABILITIES_MULTI_STRIKE_DEF"],
        SpecialAbilitiesPhysicalShieldDef => ["SPECIAL_ABILITIES_PHYSICAL_SHIELD_DEF"],
        SpecialAbilitiesSummonSpellDef => ["SPECIAL_ABILITIES_SUMMON_SPELL_DEF"],
        SpecialAbilitiesThunderLightningStormDef => ["SPECIAL_ABILITIES_THUNDER_LIGHTNING_STORM_DEF"],
        SpecialAbilitiesTurncoatSpellDef => ["SPECIAL_ABILITIES_TURNCOAT_SPELL_DEF"],
        SpecialAbilitiesUnholyPowerDef => ["SPECIAL_ABILITIES_DIVINE_WRATH_DEF", "SPECIAL_ABILITIES_UNHOLY_POWER_DEF"],
        SpecialEffectsDef => ["CSpecialEffectsDef"],
        SpotLightDef => ["CSpotLightDef"],
        StealthDef => ["CStealthDef"],
        StockItemDef => ["CStockItemDef"],
        SummonDef => ["CSummonDef"],
        SummonableCreatureDef => ["CSummonableCreatureDef"],
        SummonerDef => ["CSummonerDef"],
        TCVolumeContainmentTrackerDef => ["CTCVolumeContainmentTrackerDef"],
        TargetingDef => ["CTargetingDef"],
        TattooDef => ["CTattooDef"],
        TavernDef => ["CTavernDef"],
        TavernGameCardBaseDef => ["CTavernGameCardBaseDef"],
        TavernGameCoinBaseDef => ["CTavernGameCoinBaseDef"],
        TavernGameCoinGolfDef => ["CTavernGameCoinGolfDef"],
        TavernGameDef => ["CTavernGameDef"],
        TavernGameShoveHaPennyDef => ["CTavernGameShoveHaPennyDef"],
        TavernGameSpotTheAdditionDef => ["CTavernGameSpotTheAdditionDef"],
        TavernTableDef => ["CTavernTableDef"],
        TeleporterDef => ["CTeleporterDef"],
        TextureReplacementDef => ["CTextureReplacementDef"],
        ThingBaseDef => ["THING"],
        ThingBuildingDef => ["BUILDING"],
        ThingCreatureDef => ["CREATURE"],
        ThingDrainLifeShotDef => ["CThingDrainLifeShotDef"],
        ThingHolySiteDef => ["HOLY_SITE"],
        ThingMarkerDef => ["MARKER"],
        ThingMultiArrowShotDef => ["CThingMultiArrowShotDef"],
        ThingNoiseDef => ["NOISE"],
        ThingObjectDef => ["OBJECT"],
        ThingPhysicalSwitchDef => ["PHYSICAL_SWITCH"],
        ThingShotDef => ["SHOT"],
        ThingSwitchDef => ["SWITCH"],
        ThingVillageDef => ["VILLAGE"],
        ThunderBattleDef => ["CThunderBattleDef"],
        TimeAppearanceFadeDef => ["CTimeAppearanceFadeDef"],
        TrapDef => ["CTrapDef"],
        TrollBattleDef => ["CTrollBattleDef"],
        TrophyDef => ["CTrophyDef"],
        TurncoatDef => ["CTurncoatDef"],
        UILocaleGraphicsDef => ["UI_LOCALE_GRAPHICS_DEF"],
        UiMiscThingsDef => ["UI_MISC_THINGS_DEF"],
        VillageDef => ["CVillageDef"],
        VillageMemberDef => ["CVillageMemberDef"],
        VillagePeopleDef => ["CVillagePeopleDef"],
        VillagerInteractionsDef => ["VILLAGER_INTERACTION"],
        WallMountEffectsDef => ["CWallMountEffectsDef"],
        WaspQueenBattleDef => ["CWaspQueenBattleDef"],
        WeaponDef => ["CWeaponDef"],
        WhisperBattleDef => ["CWhisperBattleDef"],
        WifeDef => ["CWifeDef"],
        WillResponseDef => ["CWillResponseDef"],
        DegradableDef => ["CDegradableDef"],
        ReplaceableMeshDef => ["CReplaceableMeshDef"],
        GlobalDef => ["GLOBAL"],
        PlayerMovementDef => ["PLAYER_MOVEMENT"],
        AppearanceModifierDef => ["CAppearanceModifierDef"],
        ShopDef => ["CShopDef"],
        ShopItemDef => ["CShopItemDef"],
        }
    };
}
