use crate::def_struct;

def_struct! {
    /// `ENVIRONMENT` — C++ `CEnvironmentDef`.
    #[derive(Debug, Clone, PartialEq)]
    pub struct EnvironmentDef {
        "ColourLookupTexture" => pub colour_lookup_texture: String,
        "DiffuseLookupRow" => pub diffuse_lookup_row: i32,
        "AmbientLookupRow" => pub ambient_lookup_row: i32,
        "BacklightLookupRow" => pub backlight_lookup_row: i32,
        "ReflectionLookupRow" => pub reflection_lookup_row: i32,
        "MistEffectColourLookupRow" => pub mist_effect_colour_lookup_row: i32,
        "FogColourLookupRow" => pub fog_colour_lookup_row: i32,
        "FogAlphaLookupRow" => pub fog_alpha_lookup_row: i32,
        "SunColourLookupRow" => pub sun_colour_lookup_row: i32,
        "CloudColourLookupRow" => pub cloud_colour_lookup_row: i32,
        "MoonColourLookupRow" => pub moon_colour_lookup_row: i32,
        "StarsColourLookupRow" => pub stars_colour_lookup_row: i32,
        "SunFlareColourLookupRow" => pub sun_flare_colour_lookup_row: i32,
        "LensFlareColourLookupRow" => pub lens_flare_colour_lookup_row: i32,
        "SkyGradientTopLookupRow" => pub sky_gradient_top_lookup_row: i32,
        "SkyGradientTopAlphaLookupRow" => pub sky_gradient_top_alpha_lookup_row: i32,
        "SkyGradientBottomLookupRow" => pub sky_gradient_bottom_lookup_row: i32,
        "SkyGradientBottomAlphaLookupRow" => pub sky_gradient_bottom_alpha_lookup_row: i32,
        "SunlightAttenuatorColourLookupRow" => pub sunlight_attenuator_colour_lookup_row: i32,
        "DiffuseClampAngle" => pub diffuse_clamp_angle: f32,
        "SunlightAttenuatorAngleFadeStart" => pub sunlight_attenuator_angle_fade_start: f32,
        "SunlightAttenuatorAngleFadeEnd" => pub sunlight_attenuator_angle_fade_end: f32,
        "WaterColourLookupRow" => pub water_colour_lookup_row: i32,
        "SeaColourLookupRow" => pub sea_colour_lookup_row: i32,
        "GlowThresholdColourLookupRow" => pub glow_threshold_colour_lookup_row: i32,
        "GlowBloomColourLookupRow" => pub glow_bloom_colour_lookup_row: i32,
        "SeaTexture" => pub sea_texture: i32,
        "SeaRadius" => pub sea_radius: i32,
        "SeaFlatSectionStart" => pub sea_flat_section_start: i32,
        "SeaFlatSectionEnd" => pub sea_flat_section_end: i32,
        "DayStartTime" => pub day_start_time: f32,
        "DaySpeed" => pub day_speed: f32,
        "MistAlphaGraphic" => pub mist_alpha_graphic: i32,
        "MistAlphaGraphicPC" => pub mist_alpha_graphic_pc: i32,
        "IceBumpMap" => pub ice_bump_map: i32,
        "IceBumpMapPC" => pub ice_bump_map_pc: i32,
        "IceTexture" => pub ice_texture: i32,
        "WaterEdgeAlphaMap" => pub water_edge_alpha_map: i32,
        "WaterSurfMap" => pub water_surf_map: i32,
        "WaterBumpMapPC" => pub water_bump_map_pc: i32,
        "WaterBumpMap" => pub water_bump_map: i32,
        "WaterBumpMap2" => pub water_bump_map2: i32,
        "SeaBumpMapPC" => pub sea_bump_map_pc: i32,
        "SeaBumpMap" => pub sea_bump_map: i32,
        "SeaBumpMap2" => pub sea_bump_map2: i32,
        "WaterEnvMapOverlayTexture" => pub water_env_map_overlay_texture: i32,
        "RainTexture" => pub rain_texture: i32,
        "RainTexturePC" => pub rain_texture_pc: i32,
        "SnowTexture" => pub snow_texture: i32,
        "RainSplashParticle" => pub rain_splash_particle: i32,
        "LightningFadeInDuration" => pub lightning_fade_in_duration: f32,
        "LightningFadeOutDuration" => pub lightning_fade_out_duration: f32,
        "LightningFlashDuration" => pub lightning_flash_duration: f32,
        "LightningRainThreshold" => pub lightning_rain_threshold: f32,
        "LightningTheme" => pub lightning_theme: i32,
        "CloudSpeedMultiplier" => pub cloud_speed_multiplier: f32,
        "CloudMaxSpeed" => pub cloud_max_speed: f32,
        "CloudTextureCoordMultiplier" => pub cloud_texture_coord_multiplier: f32,
        "CloudTextureCoordOffset" => pub cloud_texture_coord_offset: f32,
        "CloudHeightOffset" => pub cloud_height_offset: f32,
        "WaterLakeMinimumFlowSpeed" => pub water_lake_minimum_flow_speed: f32,
        "WaterLakeMaximumFlowSpeed" => pub water_lake_maximum_flow_speed: f32,
    }
}

