use crate::def_struct;
use crate::def::prelude::*;

def_struct! {
    /// `GLOBAL` — C++ `CGlobalDef`.
    #[derive(Debug, Clone, PartialEq)]
    pub struct GlobalDef {
        "ControlSchemePC" => pub control_scheme_pc: DefIndex,
        "ControlSchemePCAggressive" => pub control_scheme_pc_aggressive: DefIndex,
        "ControlSchemeXBOX" => pub control_scheme_xbox: DefIndex,
        "ControlSchemeXBOXAggressive" => pub control_scheme_xbox_aggressive: DefIndex,
        "PhysicsTexture" => pub physics_texture: i32,
        "InvalidThemeStandin" => pub invalid_theme_standin: DefIndex,
        "DefaultEngineThemeDef" => pub default_engine_theme_def: DefIndex,
        "StaticMapGenerationEstimatedMaxCameraHeightAboveLandscape" => pub static_map_generation_estimated_max_camera_height_above_landscape: f32,
        "GraphicWeaponTrail" => pub graphic_weapon_trail: i32,
        "GraphicWeaponTrail2" => pub graphic_weapon_trail2: i32,
        "GraphicWeaponTrailArrow" => pub graphic_weapon_trail_arrow: i32,
        "WeaponTrailAlpha" => pub weapon_trail_alpha: i32,
        "WeaponTrailAlphaFadeOffTime" => pub weapon_trail_alpha_fade_off_time: f32,
        "WeaponTrailArrowAlpha" => pub weapon_trail_arrow_alpha: i32,
        "WeaponTrailArrowAlphaFadeOffTime" => pub weapon_trail_arrow_alpha_fade_off_time: f32,
        "WeaponTrialNumFramesToFadeOut" => pub weapon_trial_num_frames_to_fade_out: i32,
        "HealthPickupValue" => pub health_pickup_value: i32,
        "RespawnDelay" => pub respawn_delay: i32,
        "ScrabbleAngle" => pub scrabble_angle: i32,
        "SlideAngle" => pub slide_angle: i32,
        "MaxFollowers" => pub max_followers: i32,
        "PickupGoldSoundCriteria" => pub pickup_gold_sound_criteria: String,
        "PickupItemSoundCriteria" => pub pickup_item_sound_criteria: String,
        "OnClickSoundCriteria" => pub on_click_sound_criteria: String,
        "EditorSpangleCursor" => pub editor_spangle_cursor: i32,
        "EditorCircleSprite" => pub editor_circle_sprite: i32,
        "EditorSecondaryCircleSprite" => pub editor_secondary_circle_sprite: i32,
        "TestSpeech" => pub test_speech: i32,
        "MimeSpeechIndex" => pub mime_speech_index: String,
        "AdultSleepTimeStart" => pub adult_sleep_time_start: i32,
        "AdultSleepTimeEnd" => pub adult_sleep_time_end: i32,
        "ChildSleepTimeStart" => pub child_sleep_time_start: i32,
        "ChildSleepTimeEnd" => pub child_sleep_time_end: i32,
        "ElderlySleepTimeStart" => pub elderly_sleep_time_start: i32,
        "ElderlySleepTimeEnd" => pub elderly_sleep_time_end: i32,
        "CreatureGeneratorRegenDelaySeconds" => pub creature_generator_regen_delay_seconds: f32,
        "Music" => pub music: i32,
        "AgeIncreasePerLevelUp" => pub age_increase_per_level_up: f32,
        "E3BodgeFireflyGraphic" => pub e3_bodge_firefly_graphic: i32,
        "SwitchGraphic" => pub switch_graphic: EngineGraphic,
        "TrackGraphic" => pub track_graphic: EngineGraphic,
        "ConversationCameras" => pub conversation_cameras: VecMap<i32, String>,
        "PermittedAINarrators" => pub permitted_ai_narrators: Vec<String>,
        "DialogueLayers" => pub dialogue_layers: Vec<DialogueLayerDef>,
        "OpinionDebugIndicatorIcon" => pub opinion_debug_indicator_icon: i32,
        "WifeLoveIndicatorIcon" => pub wife_love_indicator_icon: i32,
        "WifeEngagedIndicatorIcon" => pub wife_engaged_indicator_icon: i32,
        "WifeMarriedIndicatorIcon" => pub wife_married_indicator_icon: i32,
        "ExpressionIndicatorIcon" => pub expression_indicator_icon: i32,
        "FollowerIndicatorIcon" => pub follower_indicator_icon: i32,
        "EmoteIconDrawDistance" => pub emote_icon_draw_distance: f32 = 24.0,
        "AngleToBeConsideredVertical" => pub angle_to_be_considered_vertical: f32,
        "SoundGainLowerValueWhenInsideOutside" => pub sound_gain_lower_value_when_inside_outside: f32,
        "TeleportOutParticleEffect" => pub teleport_out_particle_effect: i32,
        "TeleportFadeOutTimeInSeconds" => pub teleport_fade_out_time_in_seconds: f32,
        "TeleportInParticleEffect" => pub teleport_in_particle_effect: i32,
        "TeleportFadeInTimeInSeconds" => pub teleport_fade_in_time_in_seconds: f32,
        "DamageForMaximumBlood" => pub damage_for_maximum_blood: f32,
    }
}
