use crate::def_struct;
use crate::def::prelude::*;

def_struct! {
    /// `HERO_STATS` — C++ `CHeroStatsDef`.
    #[derive(Debug, Clone, PartialEq)]
    pub struct HeroStatsDef {
        "MaximumStamina" => pub maximum_stamina: i32,
        "NumberOfSecondsAfterUseStaminaStartsRefilling" => pub number_of_seconds_after_use_stamina_starts_refilling: f32,
        "NumberOfSecondsAfterChangeHealthStartsRefilling" => pub number_of_seconds_after_change_health_starts_refilling: f32,
        "NumberOfSecondsBetweenHealthRefills" => pub number_of_seconds_between_health_refills: f32,
        "StaminaToRegainPerSecond" => pub stamina_to_regain_per_second: i32,
        "HealthToRegainPerRefill" => pub health_to_regain_per_refill: i32,
        "RenownLossOnDeath" => pub renown_loss_on_death: i32,
        "MoneyLossOnDeath" => pub money_loss_on_death: i32,
        "MaximumMoney" => pub maximum_money: i32,
        "MaximumExpToSpend" => pub maximum_exp_to_spend: i32,
        "ExpToSpendAtWhichToDisplayTutorial" => pub exp_to_spend_at_which_to_display_tutorial: i32,
        "MinAge" => pub min_age: f32,
        "MaxAge" => pub max_age: f32,
        "AppearanceModifierScaling" => pub appearance_modifier_scaling: Vec<AppearanceModifierScalingDef>,
        "AmountFatnessIncreasesPerPointOfOverEating" => pub amount_fatness_increases_per_point_of_over_eating: f32,
        "NumberOfMinutesBetweenFatnessReductions" => pub number_of_minutes_between_fatness_reductions: f32,
        "AmountFatnessDecreasesPerReduction" => pub amount_fatness_decreases_per_reduction: f32,
        "DrinkAffectMultiplierMultiplier" => pub drink_affect_multiplier_multiplier: f32,
        "MinVomitTime" => pub min_vomit_time: i32,
        "MaxVomitTime" => pub max_vomit_time: i32,
        "MinTimeBeforeVomiting" => pub min_time_before_vomiting: i32,
        "MaxTimeBeforeVomiting" => pub max_time_before_vomiting: i32,
        "PintsOfSobrietyPerSecondOfPuke" => pub pints_of_sobriety_per_second_of_puke: f32,
        "PintsToDrunk" => pub pints_to_drunk: f32,
        "PintsToVomit" => pub pints_to_vomit: f32,
        "AlcoholAbsorbtionPerSecond" => pub alcohol_absorbtion_per_second: f32,
        "RenownLevelCosts" => pub renown_level_costs: Vec<i32>,
        "RenownLevelMaxFollowers" => pub renown_level_max_followers: Vec<i32>,
        "RenownLevelMaxBoastingCrowd" => pub renown_level_max_boasting_crowd: Vec<i32>,
        "MaxMorality" => pub max_morality: i32,
        "MaxMoralityAsChild" => pub max_morality_as_child: i32,
        "MaxExtraMaxHitPoints" => pub max_extra_max_hit_points: f32,
        "MaxExtraMaxStaminaPoints" => pub max_extra_max_stamina_points: i32,
        "MoralityChangeOnTheftFromHome" => pub morality_change_on_theft_from_home: i32,
        "MoralityChangeOnTheftFromShop" => pub morality_change_on_theft_from_shop: i32,
        "MoralityChangeOnVandalism" => pub morality_change_on_vandalism: i32,
        "MoralityChangeOnPicklock" => pub morality_change_on_picklock: i32,
        "TradeSkillForGuileLevel" => pub trade_skill_for_guile_level: Vec<f32>,
        "StatLevels" => pub stat_levels: Vec<AbilityTrackDef>,
        "MaxHitPointsPerHealthLevel" => pub max_hit_points_per_health_level: Vec<f32>,
        "MaxStaminaPointsPerMagicPowerLevel" => pub max_stamina_points_per_magic_power_level: Vec<i32>,
        "SoundDistanceMultiplierPerStealthLevel" => pub sound_distance_multiplier_per_stealth_level: Vec<f32>,
        "VisibilityMultiplierPerStealthLevel" => pub visibility_multiplier_per_stealth_level: Vec<f32>,
    }
}
