use crate::def_struct;
use crate::def::prelude::*;

def_struct! {
    /// `HERO_COMBAT` — C++ `CHeroCombatDef`.
    #[derive(Debug, Clone, PartialEq)]
    pub struct HeroCombatDef {
        "RangedAccuracySecondsForMaximumWithSkill" => pub ranged_accuracy_seconds_for_maximum_with_skill: FloatRange,
        "RangedAccuracyPercentFractionWithBuildup" => pub ranged_accuracy_percent_fraction_with_buildup: FloatRange,
        "RangedAccuracyPercentWithStats" => pub ranged_accuracy_percent_with_stats: FloatRange,
        "RangedAccuracyWeighting" => pub ranged_accuracy_weighting: VecMap<Opinion, f32>,
        "RangedAccuracyShakeyCursor" => pub ranged_accuracy_shakey_cursor: FloatRange,
        "RangedAccuracyShakeyCursorWeighting" => pub ranged_accuracy_shakey_cursor_weighting: VecMap<Opinion, f32>,
        "RangedAccuracyShakeFractionOfRadius" => pub ranged_accuracy_shake_fraction_of_radius: f32,
        "RangedDamageMultiplierWeighting" => pub ranged_damage_multiplier_weighting: VecMap<Opinion, f32>,
        "RangedDamageMultiplierSpeedWithStatParameter" => pub ranged_damage_multiplier_speed_with_stat_parameter: f32,
        "RangedDamageMultiplierSpeedWithDistance" => pub ranged_damage_multiplier_speed_with_distance: f32,
        "RangedDamageMultiplierSpeedNominalBuildup" => pub ranged_damage_multiplier_speed_nominal_buildup: f32,
        "RangedDamageMultiplierScaleNominalBuildup" => pub ranged_damage_multiplier_scale_nominal_buildup: f32,
        "RangedDamageMultiplierSpeedSuperBuildup" => pub ranged_damage_multiplier_speed_super_buildup: f32,
        "RangedDamageMultiplierScaleSuperBuildup" => pub ranged_damage_multiplier_scale_super_buildup: f32,
        "RangedWeaponReloadSpeedWeighting" => pub ranged_weapon_reload_speed_weighting: VecMap<Opinion, f32>,
        "MeleeDamageMultiplierWithStats" => pub melee_damage_multiplier_with_stats: FloatRange,
        "MeleeDamageWeighting" => pub melee_damage_weighting: VecMap<Opinion, f32>,
        "HitDamageMultiplierWithStats" => pub hit_damage_multiplier_with_stats: FloatRange,
        "HitDamageWeighting" => pub hit_damage_weighting: VecMap<Opinion, f32>,
        "MeleeFlourishValidOnMultiplierLevelIncrease" => pub melee_flourish_valid_on_multiplier_level_increase: bool,
        "MeleeFlourishNumMultiplierLevelsPerFlourish" => pub melee_flourish_num_multiplier_levels_per_flourish: i32,
        "MeleeFlourishAllowBreakingOfRotation" => pub melee_flourish_allow_breaking_of_rotation: bool,
        "MeleeFlourishSecondsForAvailibility" => pub melee_flourish_seconds_for_availibility: f32,
        "MeleeFlourishOneShot" => pub melee_flourish_one_shot: bool,
        "MeleeFlourishUsable" => pub melee_flourish_usable: bool,
        "MeleeCombatPlayStrikeSounds" => pub melee_combat_play_strike_sounds: bool,
        "TargetingPressureFractionThresholdForToggle" => pub targeting_pressure_fraction_threshold_for_toggle: f32,
        "MaxAngleToTurnToShootAtTargetInThirdPersonBowMode" => pub max_angle_to_turn_to_shoot_at_target_in_third_person_bow_mode: f32,
        "MeleeStrikeNumFramesPauseOnHeroStrike" => pub melee_strike_num_frames_pause_on_hero_strike: i32,
        "MeleeStrikeAnimationSpeedFractionWithStats" => pub melee_strike_animation_speed_fraction_with_stats: FloatRange,
        "MeleeStrikeAnimationSpeedWeighting" => pub melee_strike_animation_speed_weighting: VecMap<Opinion, f32>,
        "AutoBlockSkillThreshold" => pub auto_block_skill_threshold: f32,
        "AutoBlockStrengthThreshold" => pub auto_block_strength_threshold: f32,
        "MeleeRecoilMaintainHandednessSkillThreshold" => pub melee_recoil_maintain_handedness_skill_threshold: f32,
        "MeleeRecoilMaintainHandednessStrengthThreshold" => pub melee_recoil_maintain_handedness_strength_threshold: f32,
        "MeleeRecoilMaintainComboChainSkillThreshold" => pub melee_recoil_maintain_combo_chain_skill_threshold: f32,
        "MeleeRecoilMaintainComboChainStrengthThreshold" => pub melee_recoil_maintain_combo_chain_strength_threshold: f32,
        "DefaultCombatAbilities" => pub default_combat_abilities: Vec<i32>,
        "HeavyWeapons" => pub heavy_weapons: VecMap<i32, IdleStateGroup>,
        "ProjectileWeaponFirstPersonModeMaxFOVValues" => pub projectile_weapon_first_person_mode_max_fov_values: Vec<f32>,
        "ProjectileTargetingAcquireTargetTag" => pub projectile_targeting_acquire_target_tag: bool,
        "ProjectileTargetingAcquireTargetsAuto" => pub projectile_targeting_acquire_targets_auto: bool,
        "ProjectileTargetingUseAnalogueZoom" => pub projectile_targeting_use_analogue_zoom: bool,
        "ProjectileWeaponAnalogueZoomControlWeight" => pub projectile_weapon_analogue_zoom_control_weight: f32,
    }
}
