use crate::def_struct;
use crate::def::prelude::*;

def_struct! {
    /// `SPECIAL_ABILITIES_PHYSICAL_SHIELD_DEF` — C++ `CSpecialAbilitiesPhysicalShieldDef`.
    #[derive(Debug, Clone, PartialEq)]
    pub struct SpecialAbilitiesPhysicalShieldDef {
        "InitSound" => pub init_sound: DefString,
        "PowerUp1Sound" => pub power_up1_sound: DefString,
        "PowerUp2Sound" => pub power_up2_sound: DefString,
        "PowerUp3Sound" => pub power_up3_sound: DefString,
        "CastSound" => pub cast_sound: DefString,
        "LoopingSoundLevel0" => pub looping_sound_level0: DefString,
        "LoopingSoundLevel1" => pub looping_sound_level1: DefString,
        "LoopingSoundLevel2" => pub looping_sound_level2: DefString,
        "LoopingSoundLevel3" => pub looping_sound_level3: DefString,
        "EndSound" => pub end_sound: DefString,
        "Level0CamDist" => pub level0_cam_dist: f32,
        "Level1CamDist" => pub level1_cam_dist: f32,
        "Level2CamDist" => pub level2_cam_dist: f32,
        "Level3CamDist" => pub level3_cam_dist: f32,
        "Level0CamHeight" => pub level0_cam_height: f32,
        "Level1CamHeight" => pub level1_cam_height: f32,
        "Level2CamHeight" => pub level2_cam_height: f32,
        "Level3CamHeight" => pub level3_cam_height: f32,
        "Level0CamFOV" => pub level0_cam_fov: f32,
        "Level1CamFOV" => pub level1_cam_fov: f32,
        "Level2CamFOV" => pub level2_cam_fov: f32,
        "Level3CamFOV" => pub level3_cam_fov: f32,
        "Level0CamSwitchTime" => pub level0_cam_switch_time: f32,
        "Level1CamSwitchTime" => pub level1_cam_switch_time: f32,
        "Level2CamSwitchTime" => pub level2_cam_switch_time: f32,
        "Level3CamSwitchTime" => pub level3_cam_switch_time: f32,
        "Level0Health" => pub level0_health: f32,
        "Level1Health" => pub level1_health: f32,
        "Level2Health" => pub level2_health: f32,
        "Level3Health" => pub level3_health: f32,
        "LevelUpTimings0" => pub level_up_timings0: f32,
        "LevelUpTimings1" => pub level_up_timings1: f32,
        "LevelUpTimings2" => pub level_up_timings2: f32,
        "CastCamDist" => pub cast_cam_dist: f32,
        "CastCamHeight" => pub cast_cam_height: f32,
        "CastCamFOV" => pub cast_cam_fov: f32,
        "CastCamSwitchTime" => pub cast_cam_switch_time: f32,
        "MinWidth" => pub min_width: f32,
        "MaxWidth" => pub max_width: Vec<f32>,
        "ColorStartLevel1" => pub color_start_level1: Vec<f32>,
        "ColorStartLevel2" => pub color_start_level2: Vec<f32>,
        "ColorStartLevel3" => pub color_start_level3: Vec<f32>,
        "ColorStartLevel4" => pub color_start_level4: Vec<f32>,
        "ColorEnd" => pub color_end: Vec<f32>,
        "ColorHit" => pub color_hit: Vec<f32>,
        "WobbleRate" => pub wobble_rate: f32,
        "FadeOutPhysicalShieldTimeSecs" => pub fade_out_physical_shield_time_secs: f32,
        "BeenHitExtraWidth" => pub been_hit_extra_width: f32,
        "BeenHitFadeOffTimeSecs" => pub been_hit_fade_off_time_secs: f32,
        "ManaDamage" => pub mana_damage: Vec<f32>,
        "ShieldCoversCarriedItems" => pub shield_covers_carried_items: bool,
    }
}
