use crate::def_struct;
use crate::def::prelude::*;

def_struct! {
    /// `SPECIAL_ABILITIES_BULLET_TIME_DEF` — C++ `CSpecialAbilitiesBulletTimeDef`.
    #[derive(Debug, Clone, PartialEq)]
    pub struct SpecialAbilitiesBulletTimeDef {
        "Level0CamDist" => pub level0_cam_dist: f32,
        "Level1CamDist" => pub level1_cam_dist: f32,
        "Level2CamDist" => pub level2_cam_dist: f32,
        "Level3CamDist" => pub level3_cam_dist: f32,
        "Level0CamHeight" => pub level0_cam_height: f32,
        "Level1CamHeight" => pub level1_cam_height: f32,
        "Level2CamHeight" => pub level2_cam_height: f32,
        "Level3CamHeight" => pub level3_cam_height: f32,
        "Level0CamFOV" => pub level0_cam_fov: f32,
        "Level1CamFOV" => pub level1_cam_fov: f32,
        "Level2CamFOV" => pub level2_cam_fov: f32,
        "Level3CamFOV" => pub level3_cam_fov: f32,
        "Level0CamSwitchTime" => pub level0_cam_switch_time: f32,
        "Level1CamSwitchTime" => pub level1_cam_switch_time: f32,
        "Level2CamSwitchTime" => pub level2_cam_switch_time: f32,
        "Level3CamSwitchTime" => pub level3_cam_switch_time: f32,
        "SlowTimeDurationLevel0" => pub slow_time_duration_level0: f32,
        "SlowTimeDurationLevel1" => pub slow_time_duration_level1: f32,
        "SlowTimeDurationLevel2" => pub slow_time_duration_level2: f32,
        "SlowTimeDurationLevel3" => pub slow_time_duration_level3: f32,
        "BulletTimeSlowdownMultiplierLevel0" => pub bullet_time_slowdown_multiplier_level0: i32,
        "BulletTimeSlowdownMultiplierLevel1" => pub bullet_time_slowdown_multiplier_level1: i32,
        "BulletTimeSlowdownMultiplierLevel2" => pub bullet_time_slowdown_multiplier_level2: i32,
        "BulletTimeSlowdownMultiplierLevel3" => pub bullet_time_slowdown_multiplier_level3: i32,
        "LevelUpTimings0" => pub level_up_timings0: f32,
        "LevelUpTimings1" => pub level_up_timings1: f32,
        "LevelUpTimings2" => pub level_up_timings2: f32,
        "CastCamDist" => pub cast_cam_dist: f32,
        "CastCamHeight" => pub cast_cam_height: f32,
        "CastCamFOV" => pub cast_cam_fov: f32,
        "CastCamSwitchTime" => pub cast_cam_switch_time: f32,
        "ChargeSound" => pub charge_sound: DefString,
        "PowerUp1Sound" => pub power_up1_sound: DefString,
        "PowerUp2Sound" => pub power_up2_sound: DefString,
        "PowerUp3Sound" => pub power_up3_sound: DefString,
        "InitSound" => pub init_sound: DefString,
        "LoopSound" => pub loop_sound: DefString,
        "EndSound" => pub end_sound: DefString,
        "RadialBlurThresholdColR" => pub radial_blur_threshold_col_r: f32,
        "RadialBlurThresholdColG" => pub radial_blur_threshold_col_g: f32,
        "RadialBlurThresholdColB" => pub radial_blur_threshold_col_b: f32,
        "RadialBlurLength" => pub radial_blur_length: f32,
        "RadialBlurIntensityColR" => pub radial_blur_intensity_col_r: f32,
        "RadialBlurIntensityColG" => pub radial_blur_intensity_col_g: f32,
        "RadialBlurIntensityColB" => pub radial_blur_intensity_col_b: f32,
        "RadialBlurFade" => pub radial_blur_fade: f32,
        "RadialBlurRange" => pub radial_blur_range: f32,
        "RadialBlurTwist" => pub radial_blur_twist: f32,
        "RadialBlurFadeTimeSecs" => pub radial_blur_fade_time_secs: f32,
        "DamageRadialBlurThresholdColR" => pub damage_radial_blur_threshold_col_r: f32,
        "DamageRadialBlurThresholdColG" => pub damage_radial_blur_threshold_col_g: f32,
        "DamageRadialBlurThresholdColB" => pub damage_radial_blur_threshold_col_b: f32,
        "DamageRadialBlurLength" => pub damage_radial_blur_length: f32,
        "DamageRadialBlurIntensityColR" => pub damage_radial_blur_intensity_col_r: f32,
        "DamageRadialBlurIntensityColG" => pub damage_radial_blur_intensity_col_g: f32,
        "DamageRadialBlurIntensityColB" => pub damage_radial_blur_intensity_col_b: f32,
        "DamageRadialBlurFade" => pub damage_radial_blur_fade: f32,
        "DamageRadialBlurRange" => pub damage_radial_blur_range: f32,
        "DamageRadialBlurTwist" => pub damage_radial_blur_twist: f32,
        "DamageRadialBlurFadeTimeSecs" => pub damage_radial_blur_fade_time_secs: f32,
        "HeroCombatSlowness" => pub hero_combat_slowness: f32,
        "ScreenFilterAlpha" => pub screen_filter_alpha: Vec<f32>,
        "ScreenFilterSaturation" => pub screen_filter_saturation: Vec<f32>,
        "ScreenFilterContrast" => pub screen_filter_contrast: Vec<f32>,
        "ScreenFilterBrightness" => pub screen_filter_brightness: Vec<f32>,
        "ScreenFilterTintR" => pub screen_filter_tint_r: Vec<f32>,
        "ScreenFilterTintG" => pub screen_filter_tint_g: Vec<f32>,
        "ScreenFilterTintB" => pub screen_filter_tint_b: Vec<f32>,
        "ScreenFilterFadeOutSecs" => pub screen_filter_fade_out_secs: f32,
        "ScreenFilterFadeInSecs" => pub screen_filter_fade_in_secs: f32,
    }
}
