use crate::def_struct;

def_struct! {
    /// `SPECIAL_ABILITIES_BERSERK_DEF` — C++ `CSpecialAbilitiesBerserkDef`.
    #[derive(Debug, Clone, PartialEq)]
    pub struct SpecialAbilitiesBerserkDef {
        "SpeedMultiplier" => pub speed_multiplier: f32,
        "FramesToFadeOut" => pub frames_to_fade_out: i32,
        "LowerBerserkPercent" => pub lower_berserk_percent: f32,
        "TimeForThemeTransition" => pub time_for_theme_transition: f32,
        "BlurCenterFromFloor" => pub blur_center_from_floor: f32,
        "BerserkThreshold" => pub berserk_threshold: f32,
        "BerserkLength" => pub berserk_length: f32,
        "BerserkIntensity" => pub berserk_intensity: f32,
        "BerserkFade" => pub berserk_fade: f32,
        "BerserkRange" => pub berserk_range: f32,
        "BerserkTwist" => pub berserk_twist: f32,
        "TimeForRadialBlurToFadeOut" => pub time_for_radial_blur_to_fade_out: f32,
        "CameraStartDist" => pub camera_start_dist: f32,
        "CameraEndDist" => pub camera_end_dist: f32,
        "CameraStartDeltaHeight" => pub camera_start_delta_height: f32,
        "CameraEndDeltaHeight" => pub camera_end_delta_height: f32,
        "LevelUpTimings" => pub level_up_timings: Vec<f32>,
        "BerserkDamageToEnemyMultiplier" => pub berserk_damage_to_enemy_multiplier: Vec<f32>,
        "BerserkDamageToEnemyMultiplierAdditionPerHit" => pub berserk_damage_to_enemy_multiplier_addition_per_hit: f32,
        "BerserkDamageToMeMultiplier" => pub berserk_damage_to_me_multiplier: Vec<f32>,
        "BerserkDuration" => pub berserk_duration: Vec<f32>,
        "MaxIncreaseInStrength" => pub max_increase_in_strength: Vec<f32>,
        "BerserkScale" => pub berserk_scale: Vec<f32>,
        "BerserkBlastRadius" => pub berserk_blast_radius: f32,
        "CamDist" => pub cam_dist: Vec<f32>,
        "CamHeight" => pub cam_height: Vec<f32>,
        "CamFOV" => pub cam_fov: Vec<f32>,
        "CamSwitchTime" => pub cam_switch_time: Vec<f32>,
        "RumbleLevel" => pub rumble_level: Vec<f32>,
        "RumbleSmoothness" => pub rumble_smoothness: Vec<f32>,
        "RumbleAttack" => pub rumble_attack: Vec<f32>,
        "RumbleDecay" => pub rumble_decay: Vec<f32>,
        "RumbleReleaseLevelDelta" => pub rumble_release_level_delta: f32,
        "RumbleReleaseSmoothnessDelta" => pub rumble_release_smoothness_delta: f32,
        "RumbleReleaseAttackDelta" => pub rumble_release_attack_delta: f32,
        "RumbleReleaseDecayDelta" => pub rumble_release_decay_delta: f32,
        "DecapitateMaxProb" => pub decapitate_max_prob: Vec<f32>,
        "CrazyActionRadius" => pub crazy_action_radius: f32,
        "CrazyActionDamage" => pub crazy_action_damage: f32,
        "TargetNearestEnemyDistance" => pub target_nearest_enemy_distance: f32,
        "WeaponTrailAttack" => pub weapon_trail_attack: i32,
        "WeaponTrailKnockDown" => pub weapon_trail_knock_down: i32,
        "TintColorR" => pub tint_color_r: Vec<i32>,
        "TintColorG" => pub tint_color_g: Vec<i32>,
        "TintColorB" => pub tint_color_b: Vec<i32>,
        "CanBlockWhileBerserked" => pub can_block_while_berserked: bool,
        "CrazyIdleIntervalSecs" => pub crazy_idle_interval_secs: f32,
    }
}
