use crate::def_struct;
use crate::def::prelude::*;

def_struct! {
    /// `CREATURE` — C++ `CThingCreatureDef`.
    #[derive(Debug, Clone, PartialEq)]
    pub struct ThingCreatureDef {
        "Components" => pub components: ThingComponentSet,
        "AvailableInEditor" => pub available_in_editor: bool = true,
        "GameStatePersisted" => pub game_state_persisted: bool,
        "LevelLess" => pub level_less: bool,
        "IsDrawable" => pub is_drawable: bool,
        "AlwaysFrameUpdate" => pub always_frame_update: bool = true,
        "InMapSearches" => pub in_map_searches: bool = true,
        "StartKillLocked" => pub start_kill_locked: bool,
        "IsLoadableGlobal" => pub is_loadable_global: bool,
        "CanComeBetweenCameraAndObservedThing" => pub can_come_between_camera_and_observed_thing: bool = true,
        "IsVulnerableToMelee" => pub is_vulnerable_to_melee: bool,
        "Damageable" => pub damageable: bool,
        "ForceNoSerialise" => pub force_no_serialise: bool,
        "DrawWeaponTrails" => pub draw_weapon_trails: bool = true,
        "DrawProjectileWeaponTrails" => pub draw_projectile_weapon_trails: bool = true,
        "AlwaysIncludeInObjectStrikeScans" => pub always_include_in_object_strike_scans: bool,
        "DisableOcclusionTesting" => pub disable_occlusion_testing: bool,
        "DrawAfterWater" => pub draw_after_water: bool,
        "ForceRenderedLastFrameOverride" => pub force_rendered_last_frame_override: bool,
        "AddToComboMultiplierOnHit" => pub add_to_combo_multiplier_on_hit: bool,
        "GiveHeroStatChangesOnBeingHit" => pub give_hero_stat_changes_on_being_hit: bool,
        "GroupDef" => pub group_def: DefIndex,
        "RenderFadeDistance" => pub render_fade_distance: f32 = 64.0,
        "PersistenceFlags" => pub persistence_flags: DefIndex,
        "Health" => pub health: f32,
        "MinHealth" => pub min_health: f32 = -0.1,
        "MeshHeightOffset" => pub mesh_height_offset: f32,
        "MeshHeight" => pub mesh_height: f32 = 2.0,
        "MeshRadius" => pub mesh_radius: f32 = 1.0,
        "ApproxMaxMeshHeight" => pub approx_max_mesh_height: f32 = 2.0,
        "DefaultScriptName" => pub default_script_name: DefString,
        "DefaultScriptData" => pub default_script_data: DefString,
        "StunTimeMin" => pub stun_time_min: f32,
        "StunTimeMax" => pub stun_time_max: f32,
        "StunHealthThreshold" => pub stun_health_threshold: f32,
        "DazedTimeMin" => pub dazed_time_min: f32,
        "DazedTimeMax" => pub dazed_time_max: f32,
        "DazedHealthThreshold" => pub dazed_health_threshold: i32,
        "NumSecondsToPersistOnDeath" => pub num_seconds_to_persist_on_death: f32 = 30.0,
        "MaxSlowWalkingSpeed" => pub max_slow_walking_speed: f32,
        "MaxWalkingSpeed" => pub max_walking_speed: f32,
        "MaxJoggingSpeed" => pub max_jogging_speed: f32,
        "MaxRunningSpeed" => pub max_running_speed: f32,
        "MaxPushingSpeed" => pub max_pushing_speed: f32,
        "MaxFlyingSpeed" => pub max_flying_speed: f32,
        "MaxHoverSpeedSlow" => pub max_hover_speed_slow: f32,
        "MaxHoverSpeedMedium" => pub max_hover_speed_medium: f32,
        "MaxHoverSpeedFast" => pub max_hover_speed_fast: f32,
        "SpeedRandomisationFactor" => pub speed_randomisation_factor: f32,
        "MaxAcceleration" => pub max_acceleration: f32,
        "HearingRadius" => pub hearing_radius: f32,
        "FOV" => pub fov: f32,
        "Sex" => pub sex: Sex,
        "CreatureType" => pub creature_type: CreatureType,
        "NavigatorTypes" => pub navigator_types: Vec<NavigatorType>,
        "InitialWeaponDef" => pub initial_weapon_def: i32 = -1,
        "PrimaryMeleeWeaponDef" => pub primary_melee_weapon_def: i32,
        "SecondaryMeleeWeaponDef" => pub secondary_melee_weapon_def: i32,
        "RangedWeaponDef" => pub ranged_weapon_def: i32 = -1,
        "InitialSheathedWeapon" => pub initial_sheathed_weapon: i32,
        "PBrain" => pub p_brain: i32,
        "CreatureInteractionType" => pub creature_interaction_type: CreatureInteractionType,
        "Property" => pub property: ThingCreatureProperty,
        "Damage" => pub damage: f32 = 1.0,
        "DamageEffectDef" => pub damage_effect_def: i32,
        "StunnedParticle" => pub stunned_particle: i32,
        "Graphic" => pub graphic: EngineGraphic,
        "EyeGraphic" => pub eye_graphic: EngineGraphic,
        "DefaultOwner" => pub default_owner: i32,
        "ControlledMovementType" => pub controlled_movement_type: ControlledMovementType,
        "CombatTypeDef" => pub combat_type_def: i32,
        "ResetCombatTypeOnUnsheatheDefaultWeapons" => pub reset_combat_type_on_unsheathe_default_weapons: bool,
        "HeroCombatDef" => pub hero_combat_def: i32,
        "HeroCombatPCDef" => pub hero_combat_pc_def: i32,
        "CombatDiameter" => pub combat_diameter: f32,
        "DeferHitsIfBehindHitter" => pub defer_hits_if_behind_hitter: bool = true,
        "LeaderTypeDef" => pub leader_type_def: i32,
        "RecoverEvadeHitsPercent" => pub recover_evade_hits_percent: f32 = 75.0,
        "DeadBodyDecayEffect" => pub dead_body_decay_effect: i32,
        "LeaveDeadCreature" => pub leave_dead_creature: bool,
        "AbleToStrafe" => pub able_to_strafe: bool,
        "CreateDummyOnDeath" => pub create_dummy_on_death: bool,
        "ImmuneToAttack" => pub immune_to_attack: bool,
        "UseMeleeWeaponAsDefault" => pub use_melee_weapon_as_default: bool = true,
        "UnsheatheWeaponsAutomatically" => pub unsheathe_weapons_automatically: bool = true,
        "IsWillable" => pub is_willable: bool,
        "IsIndestructible" => pub is_indestructible: bool,
        "IsInvulnerableDuringGenericResponse" => pub is_invulnerable_during_generic_response: bool,
        "IsPushedByExplosions" => pub is_pushed_by_explosions: bool = true,
    }
}
