[package]
name = "explorer"
version = "0.0.1"
edition = "2021"
build = "build.rs"

[[bin]]
path = "main.rs"
name = "explorer"

[dependencies]
rfd = "0.11.4"
slint = "1.0.2"

[build-dependencies]
slint-build = "1.0.2"
