#[derive(Debug)]
#[repr(C)]
pub enum ECrime {
	CRIME_NONE = 0,
	CRIME_WEAPON_OUT = 1,
	CRIME_TRESPASS = 2,
	CRIME_VANDALISM = 3,
	CRIME_LOCKPICKING = 4,
	CRIME_PICK_POCKETS = 5,
	CRIME_THEFT = 6,
	CRIME_ASSAULT = 7,
	CRIME_GBH = 8,
	CRIME_MURDER = 9,
	CRIME_LAST = 10,
}