#[derive(Debug)]
#[repr(C)]
pub enum EGameEventPriority {
    GAME_EVENT_PRIORITY_NULL = 0,
    GAME_EVENT_PRIORITY_MIN = 1,
    GAME_EVENT_PRIORITY_LOW = 2,
    GAME_EVENT_PRIORITY_MEDIUM = 3,
    GAME_EVENT_PRIORITY_HIGH = 4,
    GAME_EVENT_PRIORITY_MAX = 5,
}