#[derive(Debug)]
#[repr(C)]
pub enum EHeroTrainableStatType {
	HERO_STAT_STRENGTH_PHYSIQUE = 0,
	HERO_STAT_STRENGTH_HEALTH = 1,
	HERO_STAT_STRENGTH_TOUGHNESS = 2,
	HERO_STAT_SKILL_SPEED = 3,
	HERO_STAT_SKILL_ACCURACY = 4,
	HERO_STAT_SKILL_STEALTH = 5,
	HERO_STAT_WILL_WEAPON_MAGIC = 6,
	HERO_STAT_WILL_ABILITY_MAGIC = 7,
	HERO_STAT_WILL_PURE_MAGIC = 8,
	HERO_STAT_WILL_MAGIC_POWER = 9,
	NUMBER_OF_TRAINABLE_HERO_STATS = 10,
}
