#[derive(Debug)]
#[repr(C)]
pub enum EMiniGameType {
	MINIGAME_NONE = 0,
	MINIGAME_FISHING = 1,
	MINIGAME_DIGGING = 2,
	MINIGAME_PICKPOCKET = 3,
	MINIGAME_PICKLOCK = 4,
	MINIGAME_STEAL = 5,
	MINIGAME_TROPHY = 6,
	MINIGAME_ORACLE = 7,
}