#[derive(Debug)]
#[repr(C)]
pub enum EMorality {
	MORALITY_SUPER_EVIL = 0,
	MORALITY_VERY_EVIL = 1,
	MORALITY_EVIL = 2,
	MORALITY_NEUTRAL = 3,
	MORALITY_GOOD = 4,
	MORALITY_VERY_GOOD = 5,
	MORALITY_SUPER_GOOD = 6,
}