#[derive(Debug)]
#[repr(C)]
pub enum EOpinionAttitudeType {
	OPINION_ATTITUDE_TYPE_NONE = 0,
	OPINION_ATTITUDE_TYPE_RESPECT = 1,
	OPINION_ATTITUDE_TYPE_AWE = 2,
	OPINION_ATTITUDE_TYPE_DISDAIN = 3,
	OPINION_ATTITUDE_TYPE_FEAR = 4,
	OPINION_ATTITUDE_TYPE_FRIENDLINESS = 5,
	OPINION_ATTITUDE_TYPE_WORSHIP = 6,
	OPINION_ATTITUDE_TYPE_RIDICULOUS = 7,
	OPINION_ATTITUDE_TYPE_OFFENSIVE = 8,
	OPINION_ATTITUDE_TYPE_AGREEABLE = 9,
	OPINION_ATTITUDE_TYPE_UGLY = 10,
	OPINION_ATTITUDE_TYPE_ATTRACTED = 11,
	OPINION_ATTITUDE_TYPE_LOVE = 12,
	// OPINION_ATTITUDE_TYPE_WIFE_FIRST = 13,
	OPINION_ATTITUDE_TYPE_WIFE_LOVE = 13,
	OPINION_ATTITUDE_TYPE_WIFE_LIKE = 14,
	OPINION_ATTITUDE_TYPE_WIFE_NEUTRAL = 15,
	OPINION_ATTITUDE_TYPE_WIFE_DISLIKE = 16,
	OPINION_ATTITUDE_TYPE_WIFE_HATE = 17,
	OPINION_ATTITUDE_TYPE_LAST = 18,
}