#[derive(Debug)]
#[repr(C)]
pub enum EOpinionPostDeedType {
	OPINION_POST_DEED_TYPE_NULL = 0,
	OPINION_POST_DEED_TYPE_RECIPIENT = 1,
	OPINION_POST_DEED_TYPE_WITNESSES = 2,
	OPINION_POST_DEED_TYPE_VILLAGE = 4,
	OPINION_POST_DEED_TYPE_GUARDS = 16,
	OPINION_POST_DEED_TYPE_RECIPIENT_AND_WITNESSES = 3,
	OPINION_POST_DEED_TYPE_ALL = 7,
}