#[derive(Debug)]
#[repr(C)]
pub enum ERegionLoadStatus {
    NOT_LOADING_REGION = 0,
    WAITING_FOR_LOCKED_REGION_CONFIRMATION = 1,
    WAITING_FOR_CONFIRMATION = 2,
    WAITING_FOR_TELEPORT_EFFECT = 3,
    READY_TO_BEGIN_FADE_OUT = 4,
    WAITING_FOR_FADE_OUT = 5,
    LOADING_NEW_REGION = 6,
    LOADING_RESOURCES = 7,
    READY_FOR_FADE_IN = 8,
    WAITING_FOR_FADE_IN = 9,
}