#[derive(Debug)]
#[repr(C)]
pub enum EScriptingStateGroups {
	ESSG_NONE = 0,
	ESSG_PERFORM_ACTION_PHYSICAL = 1,
	ESSG_PERFORM_ACTION_VERBAL = 2,
	ESSG_PERFORM_ACTION_AURAL = 3,
	ESSG_WANDER_NEAR = 4,
	ESSG_FOLLOW_PATH = 5,
	ESSG_FOLLOW_RANDOM = 6,
	ESSG_FOLLOW_NEAREST = 7,
	ESSG_WALK_TO_RANDOM = 8,
	ESSG_WALK_TO_NEAREST_DIFFERENT = 9,
	ESSG_RUN_AT_HERO_AND_ATTACK_UNTIL_DEAD = 10,
}