#[derive(Debug)]
#[repr(C)]
pub enum EScriptAIPriority {
	SCRIPT_AI_PRIORITY_LOWEST = 0,
	SCRIPT_AI_PRIORITY_LOW = 1,
	SCRIPT_AI_PRIORITY_MEDIUM = 2,
	SCRIPT_AI_PRIORITY_HIGH = 3,
	SCRIPT_AI_PRIORITY_HIGHEST = 4,
}