#[derive(Debug)]
#[repr(C)]
pub enum ETargetingType {
	TARGETING_NULL = 0,
	TARGETING_USABLE = 1,
	TARGETING_TALKABLE = 2,
	TARGETING_STAB = 4,
	TARGETING_SHOOTABLE = 8,
	TARGETING_MELEE = 16,
	TARGETING_ZTARGETING = 32,
}