#[derive(Debug)]
#[repr(C)]
pub enum ETextGroupSelectionMethod {
	GROUP_SELECT_NONE = 0,
	GROUP_SELECT_RANDOM = 1,
	GROUP_SELECT_RANDOM_NO_REPEAT = 2,
	GROUP_SELECT_SEQUENTIAL = 3,
	GROUP_SELECT_FIRST_ONLY = 4,
}