[package]
name = "open_albion"
version = "0.1.0"
authors = ["Jamen Marz <me@jamen.dev>"]
edition = "2018"
license = "Zlib"
homepage = "https://github.com/jamen/open_albion"
repository = "https://github.com/jamen/open_albion"

[dependencies]
winit = "0.25.0"
smol = "1.2.5"
wgpu = "0.8.1"
fontdue = "0.5.2"
glam = "0.15.1"
thunderdome = "0.4.1"
vk-shader-macros = "0.2.7"
tokio = { version = "1.6.1", features = [ "rt-multi-thread" ] }
