[package]
name = "fable_data"
version = "0.1.0"
authors = ["Jamen Marz <me@jamen.dev>"]
edition = "2018"
license = "Zlib"
homepage = "https://github.com/jamen/open_albion"
repository = "https://github.com/jamen/open_albion"

[dependencies]
flate2 = "1.0.20"
bcndecode = "0.2.0"
png = "0.16.8"
lalrpop-util = { version = "0.19.6", features = [ "lexer" ] }
regex = "1.5.4"
mint = "0.5.6"
crevice = "0.6.0"
bytemuck = { version = "1.7.0", features = [ "derive" ] }

[build-dependencies]
cc = "1.0.68"
lalrpop = "0.19.6"
