[package]
name = "fable_data"
version = "0.1.0"
authors = ["Jamen Marz <me@jamen.dev>"]
edition = "2018"
license = "Zlib"
homepage = "https://github.com/jamen/open_albion"
repository = "https://github.com/jamen/open_albion"

[dependencies]
flate2 = "1.0.20"
quick-xml = "0.22.0"

[build-dependencies]
cc = "1.0.67"
